/*
 *************************************************
 *  File        : omiBSIMBULKDef.h
 *  Date        : 2024-03-15 16:24:24.632258
 *  Description : BSIMBULK data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiBSIMBULKModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* BSIMBULK model parameters, which need to be updated in omiBSIMBULKTemp.c */
  double u0;

  unsigned u0Given:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiBSIMBULKModel;

typedef struct omiBSIMBULKInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* BSIMBULK instance parameters, which need to be used in omiBSIMBULKTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiBSIMBULKInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define BBK_INST_SIZE_o  0  /* number of instance parameter (output) */

#define BBK_INST_w             101
/* Model parameter */
#define BBK_MOD_SIZE_o  1  /* number of model parameter (output) */

#define BBK_MOD_u0                             0

#define BBK_MOD_omimod                         1001

extern String    omi_bbk_inst_param_o[BBK_INST_SIZE_o];
extern double  *omi_bbk_inst_value_o;
extern String    omi_bbk_mod_param_o[BBK_MOD_SIZE_o];
extern double  *omi_bbk_mod_value_o;
extern omiSelectModelBin *omi_bbk_mod_bin;
extern parNode *omiBSIMBULKInstHeader;
extern parNode *omiBSIMBULKModelHeader;


int    omiBSIMBULKInitModelParam (omiBSIMBULKModel *pBSIMBULKModel);
int    omiBSIMBULKAssignModelParam (omiModel *pModel, omiBSIMBULKModel *pBSIMBULKModel);
ParamId omiBSIMBULKGetModelParamIdByName (String aName);
int    omiBSIMBULKSetModelParam (omiBSIMBULKModel *pBSIMBULKModel, String aName, double aValue);
int    omiBSIMBULKSetModelParamDefault (omiBSIMBULKModel *pBSIMBULKModel);
int    omiBSIMBULKPrintModel (omiModel *pModel, omiBSIMBULKModel *pBSIMBULKModel);
int    omiBSIMBULKInitInstParam (omiBSIMBULKInstance *pBSIMBULKInst);
int    omiBSIMBULKAssignInstParam (omiInstance *pInstance, omiBSIMBULKInstance *pBSIMBULKInst);
ParamId omiBSIMBULKGetInstParamIdByName (String aName);
int    omiBSIMBULKSetInstParam (omiBSIMBULKInstance *pBSIMBULKInst, String aName, double aValue);
int    omiBSIMBULKSetInstParamDefault (omiCKT *pCKT, omiBSIMBULKModel *pBSIMBULKModel, omiBSIMBULKInstance *pBSIMBULKInst);
int    omiBSIMBULKTemp (omiCKT *pCKT, omiBSIMBULKModel *pBSIMBULKModel, omiBSIMBULKInstance *pBSIMBULKInst);
int    omiBSIMBULKCheckModel (omiInstance *pInstance, omiBSIMBULKModel *pBSIMBULKModel, omiBSIMBULKInstance *pBSIMBULKInst);
void     omiBSIMBULKBuildInstParam ();
void     omiBSIMBULKBuildModelParam ();
void    omiBSIMBULKRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiBSIMBULKCoreData
{
  double gm;
  double gds;
} omiBSIMBULKCoreData;

#define BBK_CORE_DATA_SIZE  2  /* number of core data variables */
extern String  omi_bbk_core_data_param[BBK_CORE_DATA_SIZE];

/* end of omiBSIMBULKDef.h */
