/*
 *************************************************
 *  File        : omiBSIMBULKSet.c
 *  Date        : 2024-03-15 16:24:24.632411
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiBSIMBULKDef.h"

int omiBSIMBULKSetModelParamDefault (omiBSIMBULKModel *pBSIMBULKModel)

{
  if (!pBSIMBULKModel->u0Given)
    pBSIMBULKModel->u0 = 0.067;

  /*  Other Input Parameters */

  if (!pBSIMBULKModel->omimodGiven)
    pBSIMBULKModel->omimod = 0.0;

  return OMI_OK;
}


int omiBSIMBULKSetInstParamDefault (omiCKT *pCKT, omiBSIMBULKModel *pBSIMBULKModel, omiBSIMBULKInstance *pBSIMBULKInst)
{


  /*  Other Input Parameters */

  if (!pBSIMBULKInst->wGiven)
    pBSIMBULKInst->w = 1e-05;

  return OMI_OK;
}


int omiBSIMBULKPrintModel (omiModel *pModel, omiBSIMBULKModel *pBSIMBULKModel)
{
  if (!pBSIMBULKModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiBSIMBULKSet.c */
