/*
 *************************************************
 *  File        : omiBSIMBULKSetInstParam.c
 *  Date        : 2024-03-15 16:24:24.632908
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMBULKDef.h"


int omiBSIMBULKSetInstParam (omiBSIMBULKInstance *pBSIMBULKInst, String aName, double aValue)
{
  switch(omiBSIMBULKGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case BBK_INST_w:
      pBSIMBULKInst->w = aValue;
      pBSIMBULKInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMBULKSetInstParam.c */
