/*
 *************************************************
 *  File        : omiBSIMBULKSetModelParam.c
 *  Date        : 2024-03-15 16:24:24.632837
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMBULKDef.h"


int omiBSIMBULKSetModelParam (omiBSIMBULKModel *pBSIMBULKModel, String aName, double aValue)
{
  switch(omiBSIMBULKGetModelParamIdByName(aName))
  {
    case BBK_MOD_u0:
      pBSIMBULKModel->u0 = aValue;
      pBSIMBULKModel->u0Given = TRUE;
      break;

  /* Other Input parameters */

    case BBK_MOD_omimod:
      pBSIMBULKModel->omimod = aValue;
      pBSIMBULKModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMBULKSetModelParam.c */
