/*
 *************************************************
 *  File        : omiBSIMBULKInitInstParam.c
 *  Date        : 2024-03-15 16:24:24.632766
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMBULKDef.h"


int omiBSIMBULKInitInstParam (omiBSIMBULKInstance *pBSIMBULKInst)
{

  /* Other Input parameters */

  pBSIMBULKInst->wGiven=0;

  return OMI_OK;
}
/* end of omiBSIMBULKInitInstParam.c */
