/*
 *************************************************
 *  File        : omiBSIMBULKBuildParam.c
 *  Date        : 2024-03-15 16:24:24.632567
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiBSIMBULKDef.h"


/* instance parameter (output) name array */
static char   bbk_inst_param_o[BBK_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double bbk_inst_value_o[BBK_INST_SIZE_o];

/* model parameter (output) name array */
static char   bbk_mod_param_o[BBK_MOD_SIZE_o][PARAM_LEN] =
{
  "u0",
};

/* model parameter (output) value array */
static double bbk_mod_value_o[BBK_MOD_SIZE_o];

static omiSelectModelBin bbk_mod_bin;

String  omi_bbk_inst_param_o[BBK_INST_SIZE_o];
double *omi_bbk_inst_value_o = bbk_inst_value_o;
String  omi_bbk_mod_param_o[BBK_MOD_SIZE_o];
double *omi_bbk_mod_value_o = bbk_mod_value_o;
omiSelectModelBin *omi_bbk_mod_bin = &bbk_mod_bin;

parNode *omiBSIMBULKInstHeader = NULL;
parNode *omiBSIMBULKModelHeader = NULL;

void omiBSIMBULKBuildInstParam ()
{
  int i = 0;

  if (omiBSIMBULKInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiBSIMBULKInstHeader, "w", BBK_INST_w);

  for (i = 0; i < BBK_INST_SIZE_o; i++)
    omi_bbk_inst_param_o[i] = bbk_inst_param_o[i];

  return;
}


void omiBSIMBULKBuildModelParam ()
{
  int i = 0;

  if (omiBSIMBULKModelHeader != NULL)
    return;

  omiInsertNode(&omiBSIMBULKModelHeader, "u0", BBK_MOD_u0);

  /* Other Input parameters */

  omiInsertNode(&omiBSIMBULKModelHeader, "omimod", BBK_MOD_omimod);

  for (i = 0; i < BBK_MOD_SIZE_o; i++)
    omi_bbk_mod_param_o[i] = bbk_mod_param_o[i];

  return;
}

static char bbk_core_data_param[BBK_CORE_DATA_SIZE][PARAM_LEN] =
{
  "gm",
  "gds",
};

String omi_bbk_core_data_param[BBK_CORE_DATA_SIZE];

void omiBSIMBULKBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < BBK_CORE_DATA_SIZE; i++)
    omi_bbk_core_data_param[i] = bbk_core_data_param[i];

  return;
}

/* end of omiBSIMBULKBuildParam.c */
