/*
 *************************************************
 *  File        : omiBSIMBULKInitModelParam.c
 *  Date        : 2024-03-15 16:24:24.632663
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMBULKDef.h"


int omiBSIMBULKInitModelParam (omiBSIMBULKModel *pBSIMBULKModel)
{
  pBSIMBULKModel->u0Given=0;

  /* Other Input parameters */

  pBSIMBULKModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiBSIMBULKInitModelParam.c */
