/*
 *************************************************
 *  File        : omiLUTSOISetInstParam.c
 *  Date        : 2024-03-15 16:24:26.387459
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiLUTSOIDef.h"


int omiLUTSOISetInstParam (omiLUTSOIInstance *pLUTSOIInst, String aName, double aValue)
{
  switch(omiLUTSOIGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case LSOI_INST_w:
      pLUTSOIInst->w = aValue;
      pLUTSOIInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiLUTSOISetInstParam.c */
