/*
 *************************************************
 *  File        : omiLUTSOIInitInstParam.c
 *  Date        : 2024-03-15 16:24:26.386940
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiLUTSOIDef.h"


int omiLUTSOIInitInstParam (omiLUTSOIInstance *pLUTSOIInst)
{

  /* Other Input parameters */

  pLUTSOIInst->wGiven=0;

  return OMI_OK;
}
/* end of omiLUTSOIInitInstParam.c */
