/*
 *************************************************
 *  File        : omiLUTSOIDef.h
 *  Date        : 2024-03-15 16:24:26.385664
 *  Description : LUTSOI data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiLUTSOIModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* LUTSOI model parameters, which need to be updated in omiLUTSOITemp.c */
  double vfb;

  unsigned vfbGiven:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiLUTSOIModel;

typedef struct omiLUTSOIInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* LUTSOI instance parameters, which need to be used in omiLUTSOITemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiLUTSOIInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define LSOI_INST_SIZE_o  0  /* number of instance parameter (output) */

#define LSOI_INST_w             101
/* Model parameter */
#define LSOI_MOD_SIZE_o  1  /* number of model parameter (output) */

#define LSOI_MOD_vfb                            0

#define LSOI_MOD_omimod                         1001

extern String    omi_lsoi_inst_param_o[LSOI_INST_SIZE_o];
extern double  *omi_lsoi_inst_value_o;
extern String    omi_lsoi_mod_param_o[LSOI_MOD_SIZE_o];
extern double  *omi_lsoi_mod_value_o;
extern omiSelectModelBin *omi_lsoi_mod_bin;
extern parNode *omiLUTSOIInstHeader;
extern parNode *omiLUTSOIModelHeader;


int    omiLUTSOIInitModelParam (omiLUTSOIModel *pLUTSOIModel);
int    omiLUTSOIAssignModelParam (omiModel *pModel, omiLUTSOIModel *pLUTSOIModel);
ParamId omiLUTSOIGetModelParamIdByName (String aName);
int    omiLUTSOISetModelParam (omiLUTSOIModel *pLUTSOIModel, String aName, double aValue);
int    omiLUTSOISetModelParamDefault (omiLUTSOIModel *pLUTSOIModel);
int    omiLUTSOIPrintModel (omiModel *pModel, omiLUTSOIModel *pLUTSOIModel);
int    omiLUTSOIInitInstParam (omiLUTSOIInstance *pLUTSOIInst);
int    omiLUTSOIAssignInstParam (omiInstance *pInstance, omiLUTSOIInstance *pLUTSOIInst);
ParamId omiLUTSOIGetInstParamIdByName (String aName);
int    omiLUTSOISetInstParam (omiLUTSOIInstance *pLUTSOIInst, String aName, double aValue);
int    omiLUTSOISetInstParamDefault (omiCKT *pCKT, omiLUTSOIModel *pLUTSOIModel, omiLUTSOIInstance *pLUTSOIInst);
int    omiLUTSOITemp (omiCKT *pCKT, omiLUTSOIModel *pLUTSOIModel, omiLUTSOIInstance *pLUTSOIInst);
int    omiLUTSOICheckModel (omiInstance *pInstance, omiLUTSOIModel *pLUTSOIModel, omiLUTSOIInstance *pLUTSOIInst);
void     omiLUTSOIBuildInstParam ();
void     omiLUTSOIBuildModelParam ();
void    omiLUTSOIRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiLUTSOICoreData
{
  double id;
} omiLUTSOICoreData;

#define LSOI_CORE_DATA_SIZE  1  /* number of core data variables */
extern String  omi_lsoi_core_data_param[LSOI_CORE_DATA_SIZE];

/* end of omiLUTSOIDef.h */
