/*
 *************************************************
 *  File        : omiLUTSOIInitModelParam.c
 *  Date        : 2024-03-15 16:24:26.386677
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiLUTSOIDef.h"


int omiLUTSOIInitModelParam (omiLUTSOIModel *pLUTSOIModel)
{
  pLUTSOIModel->vfbGiven=0;

  /* Other Input parameters */

  pLUTSOIModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiLUTSOIInitModelParam.c */
