/*
 *************************************************
 *  File        : omiLUTSOIBuildParam.c
 *  Date        : 2024-03-15 16:24:26.386390
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiLUTSOIDef.h"


/* instance parameter (output) name array */
static char   lsoi_inst_param_o[LSOI_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double lsoi_inst_value_o[LSOI_INST_SIZE_o];

/* model parameter (output) name array */
static char   lsoi_mod_param_o[LSOI_MOD_SIZE_o][PARAM_LEN] =
{
  "vfb",
};

/* model parameter (output) value array */
static double lsoi_mod_value_o[LSOI_MOD_SIZE_o];

static omiSelectModelBin lsoi_mod_bin;

String  omi_lsoi_inst_param_o[LSOI_INST_SIZE_o];
double *omi_lsoi_inst_value_o = lsoi_inst_value_o;
String  omi_lsoi_mod_param_o[LSOI_MOD_SIZE_o];
double *omi_lsoi_mod_value_o = lsoi_mod_value_o;
omiSelectModelBin *omi_lsoi_mod_bin = &lsoi_mod_bin;

parNode *omiLUTSOIInstHeader = NULL;
parNode *omiLUTSOIModelHeader = NULL;

void omiLUTSOIBuildInstParam ()
{
  int i = 0;

  if (omiLUTSOIInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiLUTSOIInstHeader, "w", LSOI_INST_w);

  for (i = 0; i < LSOI_INST_SIZE_o; i++)
    omi_lsoi_inst_param_o[i] = lsoi_inst_param_o[i];

  return;
}


void omiLUTSOIBuildModelParam ()
{
  int i = 0;

  if (omiLUTSOIModelHeader != NULL)
    return;

  omiInsertNode(&omiLUTSOIModelHeader, "vfb", LSOI_MOD_vfb);

  /* Other Input parameters */

  omiInsertNode(&omiLUTSOIModelHeader, "omimod", LSOI_MOD_omimod);

  for (i = 0; i < LSOI_MOD_SIZE_o; i++)
    omi_lsoi_mod_param_o[i] = lsoi_mod_param_o[i];

  return;
}

static char lsoi_core_data_param[LSOI_CORE_DATA_SIZE][PARAM_LEN] =
{
  "id",
};

String omi_lsoi_core_data_param[LSOI_CORE_DATA_SIZE];

void omiLUTSOIBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < LSOI_CORE_DATA_SIZE; i++)
    omi_lsoi_core_data_param[i] = lsoi_core_data_param[i];

  return;
}

/* end of omiLUTSOIBuildParam.c */
