/*
 *************************************************
 *  File        : omiLUTSOISetModelParam.c
 *  Date        : 2024-03-15 16:24:26.387196
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiLUTSOIDef.h"


int omiLUTSOISetModelParam (omiLUTSOIModel *pLUTSOIModel, String aName, double aValue)
{
  switch(omiLUTSOIGetModelParamIdByName(aName))
  {
    case LSOI_MOD_vfb:
      pLUTSOIModel->vfb = aValue;
      pLUTSOIModel->vfbGiven = TRUE;
      break;

  /* Other Input parameters */

    case LSOI_MOD_omimod:
      pLUTSOIModel->omimod = aValue;
      pLUTSOIModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiLUTSOISetModelParam.c */
