/*
 *************************************************
 *  File        : omiLUTSOISet.c
 *  Date        : 2024-03-15 16:24:26.386037
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiLUTSOIDef.h"

int omiLUTSOISetModelParamDefault (omiLUTSOIModel *pLUTSOIModel)

{
  if (!pLUTSOIModel->vfbGiven)
    pLUTSOIModel->vfb = 0.0;

  /*  Other Input Parameters */

  if (!pLUTSOIModel->omimodGiven)
    pLUTSOIModel->omimod = 0.0;

  return OMI_OK;
}


int omiLUTSOISetInstParamDefault (omiCKT *pCKT, omiLUTSOIModel *pLUTSOIModel, omiLUTSOIInstance *pLUTSOIInst)
{


  /*  Other Input Parameters */

  if (!pLUTSOIInst->wGiven)
    pLUTSOIInst->w = 1e-06;

  return OMI_OK;
}


int omiLUTSOIPrintModel (omiModel *pModel, omiLUTSOIModel *pLUTSOIModel)
{
  if (!pLUTSOIModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiLUTSOISet.c */
