/*
 *************************************************
 *  File        : omiPSPDef.h
 *  Date        : 2024-03-15 16:24:21.153314
 *  Description : PSP data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiPSPModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* PSP model parameters, which need to be updated in omiPSPTemp.c */
  double vfbo;

  unsigned vfboGiven:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiPSPModel;

typedef struct omiPSPInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* PSP instance parameters, which need to be used in omiPSPTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiPSPInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define PSP_INST_SIZE_o  0  /* number of instance parameter (output) */

#define PSP_INST_w             101
/* Model parameter */
#define PSP_MOD_SIZE_o  1  /* number of model parameter (output) */

#define PSP_MOD_vfbo                           0

#define PSP_MOD_omimod                         1001

extern String    omi_psp_inst_param_o[PSP_INST_SIZE_o];
extern double  *omi_psp_inst_value_o;
extern String    omi_psp_mod_param_o[PSP_MOD_SIZE_o];
extern double  *omi_psp_mod_value_o;
extern omiSelectModelBin *omi_psp_mod_bin;
extern parNode *omiPSPInstHeader;
extern parNode *omiPSPModelHeader;


int    omiPSPInitModelParam (omiPSPModel *pPSPModel);
int    omiPSPAssignModelParam (omiModel *pModel, omiPSPModel *pPSPModel);
ParamId omiPSPGetModelParamIdByName (String aName);
int    omiPSPSetModelParam (omiPSPModel *pPSPModel, String aName, double aValue);
int    omiPSPSetModelParamDefault (omiPSPModel *pPSPModel);
int    omiPSPPrintModel (omiModel *pModel, omiPSPModel *pPSPModel);
int    omiPSPInitInstParam (omiPSPInstance *pPSPInst);
int    omiPSPAssignInstParam (omiInstance *pInstance, omiPSPInstance *pPSPInst);
ParamId omiPSPGetInstParamIdByName (String aName);
int    omiPSPSetInstParam (omiPSPInstance *pPSPInst, String aName, double aValue);
int    omiPSPSetInstParamDefault (omiCKT *pCKT, omiPSPModel *pPSPModel, omiPSPInstance *pPSPInst);
int    omiPSPTemp (omiCKT *pCKT, omiPSPModel *pPSPModel, omiPSPInstance *pPSPInst);
int    omiPSPCheckModel (omiInstance *pInstance, omiPSPModel *pPSPModel, omiPSPInstance *pPSPInst);
void     omiPSPBuildInstParam ();
void     omiPSPBuildModelParam ();
void    omiPSPRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiPSPCoreData
{
  double vth;
} omiPSPCoreData;

#define PSP_CORE_DATA_SIZE  1  /* number of core data variables */
extern String  omi_psp_core_data_param[PSP_CORE_DATA_SIZE];

/* end of omiPSPDef.h */
