/*
 *************************************************
 *  File        : omiPSPInitModelParam.c
 *  Date        : 2024-03-15 16:24:21.153715
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiPSPDef.h"


int omiPSPInitModelParam (omiPSPModel *pPSPModel)
{
  pPSPModel->vfboGiven=0;

  /* Other Input parameters */

  pPSPModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiPSPInitModelParam.c */
