/*
 *************************************************
 *  File        : omiPSPBuildParam.c
 *  Date        : 2024-03-15 16:24:21.153563
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiPSPDef.h"


/* instance parameter (output) name array */
static char   psp_inst_param_o[PSP_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double psp_inst_value_o[PSP_INST_SIZE_o];

/* model parameter (output) name array */
static char   psp_mod_param_o[PSP_MOD_SIZE_o][PARAM_LEN] =
{
  "vfbo",
};

/* model parameter (output) value array */
static double psp_mod_value_o[PSP_MOD_SIZE_o];

static omiSelectModelBin psp_mod_bin;

String  omi_psp_inst_param_o[PSP_INST_SIZE_o];
double *omi_psp_inst_value_o = psp_inst_value_o;
String  omi_psp_mod_param_o[PSP_MOD_SIZE_o];
double *omi_psp_mod_value_o = psp_mod_value_o;
omiSelectModelBin *omi_psp_mod_bin = &psp_mod_bin;

parNode *omiPSPInstHeader = NULL;
parNode *omiPSPModelHeader = NULL;

void omiPSPBuildInstParam ()
{
  int i = 0;

  if (omiPSPInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiPSPInstHeader, "w", PSP_INST_w);

  for (i = 0; i < PSP_INST_SIZE_o; i++)
    omi_psp_inst_param_o[i] = psp_inst_param_o[i];

  return;
}


void omiPSPBuildModelParam ()
{
  int i = 0;

  if (omiPSPModelHeader != NULL)
    return;

  omiInsertNode(&omiPSPModelHeader, "vfbo", PSP_MOD_vfbo);

  /* Other Input parameters */

  omiInsertNode(&omiPSPModelHeader, "omimod", PSP_MOD_omimod);

  for (i = 0; i < PSP_MOD_SIZE_o; i++)
    omi_psp_mod_param_o[i] = psp_mod_param_o[i];

  return;
}

static char psp_core_data_param[PSP_CORE_DATA_SIZE][PARAM_LEN] =
{
  "vth",
};

String omi_psp_core_data_param[PSP_CORE_DATA_SIZE];

void omiPSPBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < PSP_CORE_DATA_SIZE; i++)
    omi_psp_core_data_param[i] = psp_core_data_param[i];

  return;
}

/* end of omiPSPBuildParam.c */
