/*
 *************************************************
 *  File        : omiPSPSetInstParam.c
 *  Date        : 2024-03-15 16:24:21.153944
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiPSPDef.h"


int omiPSPSetInstParam (omiPSPInstance *pPSPInst, String aName, double aValue)
{
  switch(omiPSPGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case PSP_INST_w:
      pPSPInst->w = aValue;
      pPSPInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiPSPSetInstParam.c */
