/*
 *************************************************
 *  File        : omiPSPSet.c
 *  Date        : 2024-03-15 16:24:21.153463
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiPSPDef.h"

int omiPSPSetModelParamDefault (omiPSPModel *pPSPModel)

{
  if (!pPSPModel->vfboGiven)
    pPSPModel->vfbo = -1.0;

  /*  Other Input Parameters */

  if (!pPSPModel->omimodGiven)
    pPSPModel->omimod = 0.0;

  return OMI_OK;
}


int omiPSPSetInstParamDefault (omiCKT *pCKT, omiPSPModel *pPSPModel, omiPSPInstance *pPSPInst)
{


  /*  Other Input Parameters */

  if (!pPSPInst->wGiven)
    pPSPInst->w = 1e-05;

  return OMI_OK;
}


int omiPSPPrintModel (omiModel *pModel, omiPSPModel *pPSPModel)
{
  if (!pPSPModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiPSPSet.c */
