/*
 *************************************************
 *  File        : omiPSPSetModelParam.c
 *  Date        : 2024-03-15 16:24:21.153872
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiPSPDef.h"


int omiPSPSetModelParam (omiPSPModel *pPSPModel, String aName, double aValue)
{
  switch(omiPSPGetModelParamIdByName(aName))
  {
    case PSP_MOD_vfbo:
      pPSPModel->vfbo = aValue;
      pPSPModel->vfboGiven = TRUE;
      break;

  /* Other Input parameters */

    case PSP_MOD_omimod:
      pPSPModel->omimod = aValue;
      pPSPModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiPSPSetModelParam.c */
