/*
 *************************************************
 *  File        : omiPSPInitInstParam.c
 *  Date        : 2024-03-15 16:24:21.153804
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiPSPDef.h"


int omiPSPInitInstParam (omiPSPInstance *pPSPInst)
{

  /* Other Input parameters */

  pPSPInst->wGiven=0;

  return OMI_OK;
}
/* end of omiPSPInitInstParam.c */
