/*
 *************************************************
 *  File        : omiHiSIMHVInitModelParam.c
 *  Date        : 2024-03-15 16:24:21.686077
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiHiSIMHVDef.h"


int omiHiSIMHVInitModelParam (omiHiSIMHVModel *pHiSIMHVModel)
{
  pHiSIMHVModel->vfbcGiven=0;

  /* Other Input parameters */

  pHiSIMHVModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiHiSIMHVInitModelParam.c */
