/*
 *************************************************
 *  File        : omiHiSIMHVSetModelParam.c
 *  Date        : 2024-03-15 16:24:21.686245
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiHiSIMHVDef.h"


int omiHiSIMHVSetModelParam (omiHiSIMHVModel *pHiSIMHVModel, String aName, double aValue)
{
  switch(omiHiSIMHVGetModelParamIdByName(aName))
  {
    case HSMHV_MOD_vfbc:
      pHiSIMHVModel->vfbc = aValue;
      pHiSIMHVModel->vfbcGiven = TRUE;
      break;

  /* Other Input parameters */

    case HSMHV_MOD_omimod:
      pHiSIMHVModel->omimod = aValue;
      pHiSIMHVModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiHiSIMHVSetModelParam.c */
