/*
 *************************************************
 *  File        : omiHiSIMHVBuildParam.c
 *  Date        : 2024-03-15 16:24:21.685968
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiHiSIMHVDef.h"


/* instance parameter (output) name array */
static char   hsmhv_inst_param_o[HSMHV_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double hsmhv_inst_value_o[HSMHV_INST_SIZE_o];

/* model parameter (output) name array */
static char   hsmhv_mod_param_o[HSMHV_MOD_SIZE_o][PARAM_LEN] =
{
  "vfbc",
};

/* model parameter (output) value array */
static double hsmhv_mod_value_o[HSMHV_MOD_SIZE_o];

static omiSelectModelBin hsmhv_mod_bin;

String  omi_hsmhv_inst_param_o[HSMHV_INST_SIZE_o];
double *omi_hsmhv_inst_value_o = hsmhv_inst_value_o;
String  omi_hsmhv_mod_param_o[HSMHV_MOD_SIZE_o];
double *omi_hsmhv_mod_value_o = hsmhv_mod_value_o;
omiSelectModelBin *omi_hsmhv_mod_bin = &hsmhv_mod_bin;

parNode *omiHiSIMHVInstHeader = NULL;
parNode *omiHiSIMHVModelHeader = NULL;

void omiHiSIMHVBuildInstParam ()
{
  int i = 0;

  if (omiHiSIMHVInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiHiSIMHVInstHeader, "w", HSMHV_INST_w);

  for (i = 0; i < HSMHV_INST_SIZE_o; i++)
    omi_hsmhv_inst_param_o[i] = hsmhv_inst_param_o[i];

  return;
}


void omiHiSIMHVBuildModelParam ()
{
  int i = 0;

  if (omiHiSIMHVModelHeader != NULL)
    return;

  omiInsertNode(&omiHiSIMHVModelHeader, "vfbc", HSMHV_MOD_vfbc);

  /* Other Input parameters */

  omiInsertNode(&omiHiSIMHVModelHeader, "omimod", HSMHV_MOD_omimod);

  for (i = 0; i < HSMHV_MOD_SIZE_o; i++)
    omi_hsmhv_mod_param_o[i] = hsmhv_mod_param_o[i];

  return;
}

static char hsmhv_core_data_param[HSMHV_CORE_DATA_SIZE][PARAM_LEN] =
{
  "von",
};

String omi_hsmhv_core_data_param[HSMHV_CORE_DATA_SIZE];

void omiHiSIMHVBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < HSMHV_CORE_DATA_SIZE; i++)
    omi_hsmhv_core_data_param[i] = hsmhv_core_data_param[i];

  return;
}

/* end of omiHiSIMHVBuildParam.c */
