/*
 *************************************************
 *  File        : omiHiSIMHVSet.c
 *  Date        : 2024-03-15 16:24:21.685784
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiHiSIMHVDef.h"

int omiHiSIMHVSetModelParamDefault (omiHiSIMHVModel *pHiSIMHVModel)

{
  if (!pHiSIMHVModel->vfbcGiven)
    pHiSIMHVModel->vfbc = -1.0;

  /*  Other Input Parameters */

  if (!pHiSIMHVModel->omimodGiven)
    pHiSIMHVModel->omimod = 0.0;

  return OMI_OK;
}


int omiHiSIMHVSetInstParamDefault (omiCKT *pCKT, omiHiSIMHVModel *pHiSIMHVModel, omiHiSIMHVInstance *pHiSIMHVInst)
{


  /*  Other Input Parameters */

  if (!pHiSIMHVInst->wGiven)
    pHiSIMHVInst->w = 5e-06;

  return OMI_OK;
}


int omiHiSIMHVPrintModel (omiModel *pModel, omiHiSIMHVModel *pHiSIMHVModel)
{
  if (!pHiSIMHVModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiHiSIMHVSet.c */
