/*
 *************************************************
 *  File        : omiHiSIMHVInitInstParam.c
 *  Date        : 2024-03-15 16:24:21.686165
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiHiSIMHVDef.h"


int omiHiSIMHVInitInstParam (omiHiSIMHVInstance *pHiSIMHVInst)
{

  /* Other Input parameters */

  pHiSIMHVInst->wGiven=0;

  return OMI_OK;
}
/* end of omiHiSIMHVInitInstParam.c */
