/*
 *************************************************
 *  File        : omiHiSIMHVSetInstParam.c
 *  Date        : 2024-03-15 16:24:21.686331
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiHiSIMHVDef.h"


int omiHiSIMHVSetInstParam (omiHiSIMHVInstance *pHiSIMHVInst, String aName, double aValue)
{
  switch(omiHiSIMHVGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case HSMHV_INST_w:
      pHiSIMHVInst->w = aValue;
      pHiSIMHVInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiHiSIMHVSetInstParam.c */
