/*
 *************************************************
 *  File        : omiHiSIMHVDef.h
 *  Date        : 2024-03-15 16:24:21.685613
 *  Description : HiSIMHV data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiHiSIMHVModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* HiSIMHV model parameters, which need to be updated in omiHiSIMHVTemp.c */
  double vfbc;

  unsigned vfbcGiven:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiHiSIMHVModel;

typedef struct omiHiSIMHVInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* HiSIMHV instance parameters, which need to be used in omiHiSIMHVTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiHiSIMHVInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define HSMHV_INST_SIZE_o  0  /* number of instance parameter (output) */

#define HSMHV_INST_w             101
/* Model parameter */
#define HSMHV_MOD_SIZE_o  1  /* number of model parameter (output) */

#define HSMHV_MOD_vfbc                           0

#define HSMHV_MOD_omimod                         1001

extern String    omi_hsmhv_inst_param_o[HSMHV_INST_SIZE_o];
extern double  *omi_hsmhv_inst_value_o;
extern String    omi_hsmhv_mod_param_o[HSMHV_MOD_SIZE_o];
extern double  *omi_hsmhv_mod_value_o;
extern omiSelectModelBin *omi_hsmhv_mod_bin;
extern parNode *omiHiSIMHVInstHeader;
extern parNode *omiHiSIMHVModelHeader;


int    omiHiSIMHVInitModelParam (omiHiSIMHVModel *pHiSIMHVModel);
int    omiHiSIMHVAssignModelParam (omiModel *pModel, omiHiSIMHVModel *pHiSIMHVModel);
ParamId omiHiSIMHVGetModelParamIdByName (String aName);
int    omiHiSIMHVSetModelParam (omiHiSIMHVModel *pHiSIMHVModel, String aName, double aValue);
int    omiHiSIMHVSetModelParamDefault (omiHiSIMHVModel *pHiSIMHVModel);
int    omiHiSIMHVPrintModel (omiModel *pModel, omiHiSIMHVModel *pHiSIMHVModel);
int    omiHiSIMHVInitInstParam (omiHiSIMHVInstance *pHiSIMHVInst);
int    omiHiSIMHVAssignInstParam (omiInstance *pInstance, omiHiSIMHVInstance *pHiSIMHVInst);
ParamId omiHiSIMHVGetInstParamIdByName (String aName);
int    omiHiSIMHVSetInstParam (omiHiSIMHVInstance *pHiSIMHVInst, String aName, double aValue);
int    omiHiSIMHVSetInstParamDefault (omiCKT *pCKT, omiHiSIMHVModel *pHiSIMHVModel, omiHiSIMHVInstance *pHiSIMHVInst);
int    omiHiSIMHVTemp (omiCKT *pCKT, omiHiSIMHVModel *pHiSIMHVModel, omiHiSIMHVInstance *pHiSIMHVInst);
int    omiHiSIMHVCheckModel (omiInstance *pInstance, omiHiSIMHVModel *pHiSIMHVModel, omiHiSIMHVInstance *pHiSIMHVInst);
void     omiHiSIMHVBuildInstParam ();
void     omiHiSIMHVBuildModelParam ();
void    omiHiSIMHVRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiHiSIMHVCoreData
{
  double von;
} omiHiSIMHVCoreData;

#define HSMHV_CORE_DATA_SIZE  1  /* number of core data variables */
extern String  omi_hsmhv_core_data_param[HSMHV_CORE_DATA_SIZE];

/* end of omiHiSIMHVDef.h */
