/*
 *************************************************
 *  File        : omiMVSGSet.c
 *  Date        : 2024-03-15 16:24:25.796656
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiMVSGDef.h"

int omiMVSGSetModelParamDefault (omiMVSGModel *pMVSGModel)

{
  if (!pMVSGModel->vt0Given)
    pMVSGModel->vt0 = -2.72;

  /*  Other Input Parameters */

  if (!pMVSGModel->omimodGiven)
    pMVSGModel->omimod = 0.0;

  return OMI_OK;
}


int omiMVSGSetInstParamDefault (omiCKT *pCKT, omiMVSGModel *pMVSGModel, omiMVSGInstance *pMVSGInst)
{


  /*  Other Input Parameters */

  if (!pMVSGInst->wGiven)
    pMVSGInst->w = 0.00018;

  return OMI_OK;
}


int omiMVSGPrintModel (omiModel *pModel, omiMVSGModel *pMVSGModel)
{
  if (!pMVSGModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiMVSGSet.c */
