/*
 *************************************************
 *  File        : omiMVSGInitInstParam.c
 *  Date        : 2024-03-15 16:24:25.797031
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiMVSGDef.h"


int omiMVSGInitInstParam (omiMVSGInstance *pMVSGInst)
{

  /* Other Input parameters */

  pMVSGInst->wGiven=0;

  return OMI_OK;
}
/* end of omiMVSGInitInstParam.c */
