/*
 *************************************************
 *  File        : omiMVSGInitModelParam.c
 *  Date        : 2024-03-15 16:24:25.796951
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiMVSGDef.h"


int omiMVSGInitModelParam (omiMVSGModel *pMVSGModel)
{
  pMVSGModel->vt0Given=0;

  /* Other Input parameters */

  pMVSGModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiMVSGInitModelParam.c */
