/*
 *************************************************
 *  File        : omiMVSGSetInstParam.c
 *  Date        : 2024-03-15 16:24:25.797169
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiMVSGDef.h"


int omiMVSGSetInstParam (omiMVSGInstance *pMVSGInst, String aName, double aValue)
{
  switch(omiMVSGGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case MVSG_INST_w:
      pMVSGInst->w = aValue;
      pMVSGInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiMVSGSetInstParam.c */
