/*
 *************************************************
 *  File        : omiMVSGBuildParam.c
 *  Date        : 2024-03-15 16:24:25.796800
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiMVSGDef.h"


/* instance parameter (output) name array */
static char   mvsg_inst_param_o[MVSG_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double mvsg_inst_value_o[MVSG_INST_SIZE_o];

/* model parameter (output) name array */
static char   mvsg_mod_param_o[MVSG_MOD_SIZE_o][PARAM_LEN] =
{
  "vt0",
};

/* model parameter (output) value array */
static double mvsg_mod_value_o[MVSG_MOD_SIZE_o];

static omiSelectModelBin mvsg_mod_bin;

String  omi_mvsg_inst_param_o[MVSG_INST_SIZE_o];
double *omi_mvsg_inst_value_o = mvsg_inst_value_o;
String  omi_mvsg_mod_param_o[MVSG_MOD_SIZE_o];
double *omi_mvsg_mod_value_o = mvsg_mod_value_o;
omiSelectModelBin *omi_mvsg_mod_bin = &mvsg_mod_bin;

parNode *omiMVSGInstHeader = NULL;
parNode *omiMVSGModelHeader = NULL;

void omiMVSGBuildInstParam ()
{
  int i = 0;

  if (omiMVSGInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiMVSGInstHeader, "w", MVSG_INST_w);

  for (i = 0; i < MVSG_INST_SIZE_o; i++)
    omi_mvsg_inst_param_o[i] = mvsg_inst_param_o[i];

  return;
}


void omiMVSGBuildModelParam ()
{
  int i = 0;

  if (omiMVSGModelHeader != NULL)
    return;

  omiInsertNode(&omiMVSGModelHeader, "vt0", MVSG_MOD_vt0);

  /* Other Input parameters */

  omiInsertNode(&omiMVSGModelHeader, "omimod", MVSG_MOD_omimod);

  for (i = 0; i < MVSG_MOD_SIZE_o; i++)
    omi_mvsg_mod_param_o[i] = mvsg_mod_param_o[i];

  return;
}

static char mvsg_core_data_param[MVSG_CORE_DATA_SIZE][PARAM_LEN] =
{
  "idisi",
};

String omi_mvsg_core_data_param[MVSG_CORE_DATA_SIZE];

void omiMVSGBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < MVSG_CORE_DATA_SIZE; i++)
    omi_mvsg_core_data_param[i] = mvsg_core_data_param[i];

  return;
}

/* end of omiMVSGBuildParam.c */
