/*
 *************************************************
 *  File        : omiMVSGDef.h
 *  Date        : 2024-03-15 16:24:25.796499
 *  Description : MVSG data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiMVSGModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* MVSG model parameters, which need to be updated in omiMVSGTemp.c */
  double vt0;

  unsigned vt0Given:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiMVSGModel;

typedef struct omiMVSGInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* MVSG instance parameters, which need to be used in omiMVSGTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiMVSGInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define MVSG_INST_SIZE_o  0  /* number of instance parameter (output) */

#define MVSG_INST_w             101
/* Model parameter */
#define MVSG_MOD_SIZE_o  1  /* number of model parameter (output) */

#define MVSG_MOD_vt0                            0

#define MVSG_MOD_omimod                         1001

extern String    omi_mvsg_inst_param_o[MVSG_INST_SIZE_o];
extern double  *omi_mvsg_inst_value_o;
extern String    omi_mvsg_mod_param_o[MVSG_MOD_SIZE_o];
extern double  *omi_mvsg_mod_value_o;
extern omiSelectModelBin *omi_mvsg_mod_bin;
extern parNode *omiMVSGInstHeader;
extern parNode *omiMVSGModelHeader;


int    omiMVSGInitModelParam (omiMVSGModel *pMVSGModel);
int    omiMVSGAssignModelParam (omiModel *pModel, omiMVSGModel *pMVSGModel);
ParamId omiMVSGGetModelParamIdByName (String aName);
int    omiMVSGSetModelParam (omiMVSGModel *pMVSGModel, String aName, double aValue);
int    omiMVSGSetModelParamDefault (omiMVSGModel *pMVSGModel);
int    omiMVSGPrintModel (omiModel *pModel, omiMVSGModel *pMVSGModel);
int    omiMVSGInitInstParam (omiMVSGInstance *pMVSGInst);
int    omiMVSGAssignInstParam (omiInstance *pInstance, omiMVSGInstance *pMVSGInst);
ParamId omiMVSGGetInstParamIdByName (String aName);
int    omiMVSGSetInstParam (omiMVSGInstance *pMVSGInst, String aName, double aValue);
int    omiMVSGSetInstParamDefault (omiCKT *pCKT, omiMVSGModel *pMVSGModel, omiMVSGInstance *pMVSGInst);
int    omiMVSGTemp (omiCKT *pCKT, omiMVSGModel *pMVSGModel, omiMVSGInstance *pMVSGInst);
int    omiMVSGCheckModel (omiInstance *pInstance, omiMVSGModel *pMVSGModel, omiMVSGInstance *pMVSGInst);
void     omiMVSGBuildInstParam ();
void     omiMVSGBuildModelParam ();
void    omiMVSGRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiMVSGCoreData
{
  double idisi;
} omiMVSGCoreData;

#define MVSG_CORE_DATA_SIZE  1  /* number of core data variables */
extern String  omi_mvsg_core_data_param[MVSG_CORE_DATA_SIZE];

/* end of omiMVSGDef.h */
