/*
 *************************************************
 *  File        : omiMVSGSetModelParam.c
 *  Date        : 2024-03-15 16:24:25.797098
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiMVSGDef.h"


int omiMVSGSetModelParam (omiMVSGModel *pMVSGModel, String aName, double aValue)
{
  switch(omiMVSGGetModelParamIdByName(aName))
  {
    case MVSG_MOD_vt0:
      pMVSGModel->vt0 = aValue;
      pMVSGModel->vt0Given = TRUE;
      break;

  /* Other Input parameters */

    case MVSG_MOD_omimod:
      pMVSGModel->omimod = aValue;
      pMVSGModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiMVSGSetModelParam.c */
