/*
 *************************************************
 *  File        : omiASMInitModelParam.c
 *  Date        : 2024-03-15 16:24:25.249402
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiASMDef.h"


int omiASMInitModelParam (omiASMModel *pASMModel)
{
  pASMModel->voffGiven=0;

  /* Other Input parameters */

  pASMModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiASMInitModelParam.c */
