/*
 *************************************************
 *  File        : omiASMSetInstParam.c
 *  Date        : 2024-03-15 16:24:25.249758
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiASMDef.h"


int omiASMSetInstParam (omiASMInstance *pASMInst, String aName, double aValue)
{
  switch(omiASMGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case ASM_INST_w:
      pASMInst->w = aValue;
      pASMInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiASMSetInstParam.c */
