/*
 *************************************************
 *  File        : omiASMBuildParam.c
 *  Date        : 2024-03-15 16:24:25.249196
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiASMDef.h"


/* instance parameter (output) name array */
static char   asm_inst_param_o[ASM_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double asm_inst_value_o[ASM_INST_SIZE_o];

/* model parameter (output) name array */
static char   asm_mod_param_o[ASM_MOD_SIZE_o][PARAM_LEN] =
{
  "voff",
};

/* model parameter (output) value array */
static double asm_mod_value_o[ASM_MOD_SIZE_o];

static omiSelectModelBin asm_mod_bin;

String  omi_asm_inst_param_o[ASM_INST_SIZE_o];
double *omi_asm_inst_value_o = asm_inst_value_o;
String  omi_asm_mod_param_o[ASM_MOD_SIZE_o];
double *omi_asm_mod_value_o = asm_mod_value_o;
omiSelectModelBin *omi_asm_mod_bin = &asm_mod_bin;

parNode *omiASMInstHeader = NULL;
parNode *omiASMModelHeader = NULL;

void omiASMBuildInstParam ()
{
  int i = 0;

  if (omiASMInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiASMInstHeader, "w", ASM_INST_w);

  for (i = 0; i < ASM_INST_SIZE_o; i++)
    omi_asm_inst_param_o[i] = asm_inst_param_o[i];

  return;
}


void omiASMBuildModelParam ()
{
  int i = 0;

  if (omiASMModelHeader != NULL)
    return;

  omiInsertNode(&omiASMModelHeader, "voff", ASM_MOD_voff);

  /* Other Input parameters */

  omiInsertNode(&omiASMModelHeader, "omimod", ASM_MOD_omimod);

  for (i = 0; i < ASM_MOD_SIZE_o; i++)
    omi_asm_mod_param_o[i] = asm_mod_param_o[i];

  return;
}

static char asm_core_data_param[ASM_CORE_DATA_SIZE][PARAM_LEN] =
{
};

String omi_asm_core_data_param[ASM_CORE_DATA_SIZE];

void omiASMBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < ASM_CORE_DATA_SIZE; i++)
    omi_asm_core_data_param[i] = asm_core_data_param[i];

  return;
}

/* end of omiASMBuildParam.c */
