/*
 *************************************************
 *  File        : omiASMDef.h
 *  Date        : 2024-03-15 16:24:25.248744
 *  Description : ASM data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiASMModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* ASM model parameters, which need to be updated in omiASMTemp.c */
  double voff;

  unsigned voffGiven:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiASMModel;

typedef struct omiASMInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* ASM instance parameters, which need to be used in omiASMTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiASMInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define ASM_INST_SIZE_o  0  /* number of instance parameter (output) */

#define ASM_INST_w             101
/* Model parameter */
#define ASM_MOD_SIZE_o  1  /* number of model parameter (output) */

#define ASM_MOD_voff                           0

#define ASM_MOD_omimod                         1001

extern String    omi_asm_inst_param_o[ASM_INST_SIZE_o];
extern double  *omi_asm_inst_value_o;
extern String    omi_asm_mod_param_o[ASM_MOD_SIZE_o];
extern double  *omi_asm_mod_value_o;
extern omiSelectModelBin *omi_asm_mod_bin;
extern parNode *omiASMInstHeader;
extern parNode *omiASMModelHeader;


int    omiASMInitModelParam (omiASMModel *pASMModel);
int    omiASMAssignModelParam (omiModel *pModel, omiASMModel *pASMModel);
ParamId omiASMGetModelParamIdByName (String aName);
int    omiASMSetModelParam (omiASMModel *pASMModel, String aName, double aValue);
int    omiASMSetModelParamDefault (omiASMModel *pASMModel);
int    omiASMPrintModel (omiModel *pModel, omiASMModel *pASMModel);
int    omiASMInitInstParam (omiASMInstance *pASMInst);
int    omiASMAssignInstParam (omiInstance *pInstance, omiASMInstance *pASMInst);
ParamId omiASMGetInstParamIdByName (String aName);
int    omiASMSetInstParam (omiASMInstance *pASMInst, String aName, double aValue);
int    omiASMSetInstParamDefault (omiCKT *pCKT, omiASMModel *pASMModel, omiASMInstance *pASMInst);
int    omiASMTemp (omiCKT *pCKT, omiASMModel *pASMModel, omiASMInstance *pASMInst);
int    omiASMCheckModel (omiInstance *pInstance, omiASMModel *pASMModel, omiASMInstance *pASMInst);
void     omiASMBuildInstParam ();
void     omiASMBuildModelParam ();
void    omiASMRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiASMCoreData
{
} omiASMCoreData;

#define ASM_CORE_DATA_SIZE  0  /* number of core data variables */
extern String  omi_asm_core_data_param[ASM_CORE_DATA_SIZE];

/* end of omiASMDef.h */
