/*
 *************************************************
 *  File        : omiASMSet.c
 *  Date        : 2024-03-15 16:24:25.248995
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiASMDef.h"

int omiASMSetModelParamDefault (omiASMModel *pASMModel)

{
  if (!pASMModel->voffGiven)
    pASMModel->voff = -2.0;

  /*  Other Input Parameters */

  if (!pASMModel->omimodGiven)
    pASMModel->omimod = 0.0;

  return OMI_OK;
}


int omiASMSetInstParamDefault (omiCKT *pCKT, omiASMModel *pASMModel, omiASMInstance *pASMInst)
{


  /*  Other Input Parameters */

  if (!pASMInst->wGiven)
    pASMInst->w = 0.0002;

  return OMI_OK;
}


int omiASMPrintModel (omiModel *pModel, omiASMModel *pASMModel)
{
  if (!pASMModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiASMSet.c */
