/*
 *************************************************
 *  File        : omiASMInitInstParam.c
 *  Date        : 2024-03-15 16:24:25.249514
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiASMDef.h"


int omiASMInitInstParam (omiASMInstance *pASMInst)
{

  /* Other Input parameters */

  pASMInst->wGiven=0;

  return OMI_OK;
}
/* end of omiASMInitInstParam.c */
