/*
 *************************************************
 *  File        : omiASMSetModelParam.c
 *  Date        : 2024-03-15 16:24:25.249637
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiASMDef.h"


int omiASMSetModelParam (omiASMModel *pASMModel, String aName, double aValue)
{
  switch(omiASMGetModelParamIdByName(aName))
  {
    case ASM_MOD_voff:
      pASMModel->voff = aValue;
      pASMModel->voffGiven = TRUE;
      break;

  /* Other Input parameters */

    case ASM_MOD_omimod:
      pASMModel->omimod = aValue;
      pASMModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiASMSetModelParam.c */
