/*
 *************************************************
 *  File        : omiHiSIM2Def.h
 *  Date        : 2024-03-15 16:24:22.859509
 *  Description : HiSIM2 data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiHiSIM2Model
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* HiSIM2 model parameters, which need to be updated in omiHiSIM2Temp.c */
  double vfbc;

  unsigned vfbcGiven:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiHiSIM2Model;

typedef struct omiHiSIM2Instance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* HiSIM2 instance parameters, which need to be used in omiHiSIM2Temp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiHiSIM2Instance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define HSM2_INST_SIZE_o  0  /* number of instance parameter (output) */

#define HSM2_INST_w             101
/* Model parameter */
#define HSM2_MOD_SIZE_o  1  /* number of model parameter (output) */

#define HSM2_MOD_vfbc                           0

#define HSM2_MOD_omimod                         1001

extern String    omi_hsm2_inst_param_o[HSM2_INST_SIZE_o];
extern double  *omi_hsm2_inst_value_o;
extern String    omi_hsm2_mod_param_o[HSM2_MOD_SIZE_o];
extern double  *omi_hsm2_mod_value_o;
extern omiSelectModelBin *omi_hsm2_mod_bin;
extern parNode *omiHiSIM2InstHeader;
extern parNode *omiHiSIM2ModelHeader;


int    omiHiSIM2InitModelParam (omiHiSIM2Model *pHiSIM2Model);
int    omiHiSIM2AssignModelParam (omiModel *pModel, omiHiSIM2Model *pHiSIM2Model);
ParamId omiHiSIM2GetModelParamIdByName (String aName);
int    omiHiSIM2SetModelParam (omiHiSIM2Model *pHiSIM2Model, String aName, double aValue);
int    omiHiSIM2SetModelParamDefault (omiHiSIM2Model *pHiSIM2Model);
int    omiHiSIM2PrintModel (omiModel *pModel, omiHiSIM2Model *pHiSIM2Model);
int    omiHiSIM2InitInstParam (omiHiSIM2Instance *pHiSIM2Inst);
int    omiHiSIM2AssignInstParam (omiInstance *pInstance, omiHiSIM2Instance *pHiSIM2Inst);
ParamId omiHiSIM2GetInstParamIdByName (String aName);
int    omiHiSIM2SetInstParam (omiHiSIM2Instance *pHiSIM2Inst, String aName, double aValue);
int    omiHiSIM2SetInstParamDefault (omiCKT *pCKT, omiHiSIM2Model *pHiSIM2Model, omiHiSIM2Instance *pHiSIM2Inst);
int    omiHiSIM2Temp (omiCKT *pCKT, omiHiSIM2Model *pHiSIM2Model, omiHiSIM2Instance *pHiSIM2Inst);
int    omiHiSIM2CheckModel (omiInstance *pInstance, omiHiSIM2Model *pHiSIM2Model, omiHiSIM2Instance *pHiSIM2Inst);
void     omiHiSIM2BuildInstParam ();
void     omiHiSIM2BuildModelParam ();
void    omiHiSIM2RegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiHiSIM2CoreData
{
  double ids;
  double isub;
  double igidl;
  double igisl;
  double igd;
  double igs;
  double igb;
  double gm;
  double gds;
  double gmbs;
  double von;
  double vdsat;
  double qb;
  double qg;
  double qd;
  double cgg;
  double cgd;
  double cgs;
  double cbg;
  double cbs;
  double cbd;
  double cdg;
  double cdd;
  double cds;
  double cgdo;
  double cgso;
  double cgbo;
  double ibd;
  double ibs;
  double gbd;
  double gbs;
  double capbd;
  double capbs;
} omiHiSIM2CoreData;

#define HSM2_CORE_DATA_SIZE  33  /* number of core data variables */
extern String  omi_hsm2_core_data_param[HSM2_CORE_DATA_SIZE];

/* end of omiHiSIM2Def.h */
