/*
 *************************************************
 *  File        : omiHiSIM2BuildParam.c
 *  Date        : 2024-03-15 16:24:22.859851
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiHiSIM2Def.h"


/* instance parameter (output) name array */
static char   hsm2_inst_param_o[HSM2_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double hsm2_inst_value_o[HSM2_INST_SIZE_o];

/* model parameter (output) name array */
static char   hsm2_mod_param_o[HSM2_MOD_SIZE_o][PARAM_LEN] =
{
  "vfbc",
};

/* model parameter (output) value array */
static double hsm2_mod_value_o[HSM2_MOD_SIZE_o];

static omiSelectModelBin hsm2_mod_bin;

String  omi_hsm2_inst_param_o[HSM2_INST_SIZE_o];
double *omi_hsm2_inst_value_o = hsm2_inst_value_o;
String  omi_hsm2_mod_param_o[HSM2_MOD_SIZE_o];
double *omi_hsm2_mod_value_o = hsm2_mod_value_o;
omiSelectModelBin *omi_hsm2_mod_bin = &hsm2_mod_bin;

parNode *omiHiSIM2InstHeader = NULL;
parNode *omiHiSIM2ModelHeader = NULL;

void omiHiSIM2BuildInstParam ()
{
  int i = 0;

  if (omiHiSIM2InstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiHiSIM2InstHeader, "w", HSM2_INST_w);

  for (i = 0; i < HSM2_INST_SIZE_o; i++)
    omi_hsm2_inst_param_o[i] = hsm2_inst_param_o[i];

  return;
}


void omiHiSIM2BuildModelParam ()
{
  int i = 0;

  if (omiHiSIM2ModelHeader != NULL)
    return;

  omiInsertNode(&omiHiSIM2ModelHeader, "vfbc", HSM2_MOD_vfbc);

  /* Other Input parameters */

  omiInsertNode(&omiHiSIM2ModelHeader, "omimod", HSM2_MOD_omimod);

  for (i = 0; i < HSM2_MOD_SIZE_o; i++)
    omi_hsm2_mod_param_o[i] = hsm2_mod_param_o[i];

  return;
}

static char hsm2_core_data_param[HSM2_CORE_DATA_SIZE][PARAM_LEN] =
{
  "ids",
  "isub",
  "igidl",
  "igisl",
  "igd",
  "igs",
  "igb",
  "gm",
  "gds",
  "gmbs",
  "von",
  "vdsat",
  "qb",
  "qg",
  "qd",
  "cgg",
  "cgd",
  "cgs",
  "cbg",
  "cbs",
  "cbd",
  "cdg",
  "cdd",
  "cds",
  "cgdo",
  "cgso",
  "cgbo",
  "ibd",
  "ibs",
  "gbd",
  "gbs",
  "capbd",
  "capbs",
};

String omi_hsm2_core_data_param[HSM2_CORE_DATA_SIZE];

void omiHiSIM2BuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < HSM2_CORE_DATA_SIZE; i++)
    omi_hsm2_core_data_param[i] = hsm2_core_data_param[i];

  return;
}

/* end of omiHiSIM2BuildParam.c */
