/*
 *************************************************
 *  File        : omiHiSIM2SetModelParam.c
 *  Date        : 2024-03-15 16:24:22.860091
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiHiSIM2Def.h"


int omiHiSIM2SetModelParam (omiHiSIM2Model *pHiSIM2Model, String aName, double aValue)
{
  switch(omiHiSIM2GetModelParamIdByName(aName))
  {
    case HSM2_MOD_vfbc:
      pHiSIM2Model->vfbc = aValue;
      pHiSIM2Model->vfbcGiven = TRUE;
      break;

  /* Other Input parameters */

    case HSM2_MOD_omimod:
      pHiSIM2Model->omimod = aValue;
      pHiSIM2Model->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiHiSIM2SetModelParam.c */
