/*
 *************************************************
 *  File        : omiHiSIM2InitInstParam.c
 *  Date        : 2024-03-15 16:24:22.860028
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiHiSIM2Def.h"


int omiHiSIM2InitInstParam (omiHiSIM2Instance *pHiSIM2Inst)
{

  /* Other Input parameters */

  pHiSIM2Inst->wGiven=0;

  return OMI_OK;
}
/* end of omiHiSIM2InitInstParam.c */
