/*
 *************************************************
 *  File        : omiHiSIM2InitModelParam.c
 *  Date        : 2024-03-15 16:24:22.859967
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiHiSIM2Def.h"


int omiHiSIM2InitModelParam (omiHiSIM2Model *pHiSIM2Model)
{
  pHiSIM2Model->vfbcGiven=0;

  /* Other Input parameters */

  pHiSIM2Model->omimodGiven=0;

  return OMI_OK;
}
/* end of omiHiSIM2InitModelParam.c */
