/*
 *************************************************
 *  File        : omiHiSIM2SetInstParam.c
 *  Date        : 2024-03-15 16:24:22.860155
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiHiSIM2Def.h"


int omiHiSIM2SetInstParam (omiHiSIM2Instance *pHiSIM2Inst, String aName, double aValue)
{
  switch(omiHiSIM2GetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case HSM2_INST_w:
      pHiSIM2Inst->w = aValue;
      pHiSIM2Inst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiHiSIM2SetInstParam.c */
