/*
 *************************************************
 *  File        : omiHiSIM2Set.c
 *  Date        : 2024-03-15 16:24:22.859692
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiHiSIM2Def.h"

int omiHiSIM2SetModelParamDefault (omiHiSIM2Model *pHiSIM2Model)

{
  if (!pHiSIM2Model->vfbcGiven)
    pHiSIM2Model->vfbc = -1.0;

  /*  Other Input Parameters */

  if (!pHiSIM2Model->omimodGiven)
    pHiSIM2Model->omimod = 0.0;

  return OMI_OK;
}


int omiHiSIM2SetInstParamDefault (omiCKT *pCKT, omiHiSIM2Model *pHiSIM2Model, omiHiSIM2Instance *pHiSIM2Inst)
{


  /*  Other Input Parameters */

  if (!pHiSIM2Inst->wGiven)
    pHiSIM2Inst->w = 5e-06;

  return OMI_OK;
}


int omiHiSIM2PrintModel (omiModel *pModel, omiHiSIM2Model *pHiSIM2Model)
{
  if (!pHiSIM2Model->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiHiSIM2Set.c */
