/*
 *************************************************
 *  File        : omiBSIMCMGSetModelParam.c
 *  Date        : 2024-03-15 17:26:35.260071
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMCMGDef.h"


int omiBSIMCMGSetModelParam (omiBSIMCMGModel *pBSIMCMGModel, String aName, double aValue)
{
  switch(omiBSIMCMGGetModelParamIdByName(aName))
  {
    case BCMG_MOD_u0:
      pBSIMCMGModel->u0 = aValue;
      pBSIMCMGModel->u0Given = TRUE;
      break;
    case BCMG_MOD_dvtshift:
      pBSIMCMGModel->dvtshift = aValue;
      pBSIMCMGModel->dvtshiftGiven = TRUE;
      break;

  /* Other Input parameters */

    case BCMG_MOD_omimod:
      pBSIMCMGModel->omimod = aValue;
      pBSIMCMGModel->omimodGiven = TRUE;
      break;
    case BCMG_MOD_a0:
      pBSIMCMGModel->a0 = aValue;
      pBSIMCMGModel->a0Given = TRUE;
      break;
    case BCMG_MOD_b0:
      pBSIMCMGModel->b0 = aValue;
      pBSIMCMGModel->b0Given = TRUE;
      break;
    case BCMG_MOD_c0:
      pBSIMCMGModel->c0 = aValue;
      pBSIMCMGModel->c0Given = TRUE;
      break;
    case BCMG_MOD_ea0:
      pBSIMCMGModel->ea0 = aValue;
      pBSIMCMGModel->ea0Given = TRUE;
      break;
    case BCMG_MOD_d0:
      pBSIMCMGModel->d0 = aValue;
      pBSIMCMGModel->d0Given = TRUE;
      break;
    case BCMG_MOD_nox:
      pBSIMCMGModel->nox = aValue;
      pBSIMCMGModel->noxGiven = TRUE;
      break;
    case BCMG_MOD_tsimu:
      pBSIMCMGModel->tsimu = aValue;
      pBSIMCMGModel->tsimuGiven = TRUE;
      break;
    case BCMG_MOD_dagetime:
      pBSIMCMGModel->dagetime = aValue;
      pBSIMCMGModel->dagetimeGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMCMGSetModelParam.c */
