/*
 *************************************************
 *  File        : omiBSIMCMGInitInstParam.c
 *  Date        : 2024-03-15 17:26:35.259995
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMCMGDef.h"


int omiBSIMCMGInitInstParam (omiBSIMCMGInstance *pBSIMCMGInst)
{

  /* Other Input parameters */

  pBSIMCMGInst->nfinGiven=0;

  return OMI_OK;
}
/* end of omiBSIMCMGInitInstParam.c */
