/*
 *************************************************
 *  File        : omiBSIMCMGSet.c
 *  Date        : 2024-03-15 17:26:35.259634
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiBSIMCMGDef.h"

int omiBSIMCMGSetModelParamDefault (omiBSIMCMGModel *pBSIMCMGModel)

{
  if (!pBSIMCMGModel->u0Given)
    pBSIMCMGModel->u0 = 0.03;
  if (!pBSIMCMGModel->dvtshiftGiven)
    pBSIMCMGModel->dvtshift = 0.0;

  /*  Other Input Parameters */

  if (!pBSIMCMGModel->omimodGiven)
    pBSIMCMGModel->omimod = 0.0;
  if (!pBSIMCMGModel->a0Given)
    pBSIMCMGModel->a0 = 0.0;
  if (!pBSIMCMGModel->b0Given)
    pBSIMCMGModel->b0 = 0.0;
  if (!pBSIMCMGModel->c0Given)
    pBSIMCMGModel->c0 = 0.0;
  if (!pBSIMCMGModel->ea0Given)
    pBSIMCMGModel->ea0 = 0.0;
  if (!pBSIMCMGModel->d0Given)
    pBSIMCMGModel->d0 = 0.0;
  if (!pBSIMCMGModel->noxGiven)
    pBSIMCMGModel->nox = 0.15;
  if (!pBSIMCMGModel->tsimuGiven)
    pBSIMCMGModel->tsimu = 0.0;
  if (!pBSIMCMGModel->dagetimeGiven)
    pBSIMCMGModel->dagetime = 0.0;

  return OMI_OK;
}


int omiBSIMCMGSetInstParamDefault (omiCKT *pCKT, omiBSIMCMGModel *pBSIMCMGModel, omiBSIMCMGInstance *pBSIMCMGInst)
{


  /*  Other Input Parameters */

  if (!pBSIMCMGInst->nfinGiven)
    pBSIMCMGInst->nfin = 1.0;

  return OMI_OK;
}


int omiBSIMCMGPrintModel (omiModel *pModel, omiBSIMCMGModel *pBSIMCMGModel)
{
  if (!pBSIMCMGModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiBSIMCMGSet.c */
