/*
 *************************************************
 *  File        : omiBSIMCMGInitModelParam.c
 *  Date        : 2024-03-15 17:26:35.259890
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMCMGDef.h"


int omiBSIMCMGInitModelParam (omiBSIMCMGModel *pBSIMCMGModel)
{
  pBSIMCMGModel->u0Given=0;
  pBSIMCMGModel->dvtshiftGiven=0;

  /* Other Input parameters */

  pBSIMCMGModel->omimodGiven=0;
  pBSIMCMGModel->a0Given=0;
  pBSIMCMGModel->b0Given=0;
  pBSIMCMGModel->c0Given=0;
  pBSIMCMGModel->ea0Given=0;
  pBSIMCMGModel->d0Given=0;
  pBSIMCMGModel->noxGiven=0;
  pBSIMCMGModel->tsimuGiven=0;
  pBSIMCMGModel->dagetimeGiven=0;

  return OMI_OK;
}
/* end of omiBSIMCMGInitModelParam.c */
