/*
 *************************************************
 *  File        : omiBSIMCMGSetInstParam.c
 *  Date        : 2024-03-15 17:26:35.260171
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMCMGDef.h"


int omiBSIMCMGSetInstParam (omiBSIMCMGInstance *pBSIMCMGInst, String aName, double aValue)
{
  switch(omiBSIMCMGGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case BCMG_INST_nfin:
      pBSIMCMGInst->nfin = aValue;
      pBSIMCMGInst->nfinGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMCMGSetInstParam.c */
