/*
 *************************************************
 *  File        : omiBSIMCMGDef.h
 *  Date        : 2024-03-15 17:26:35.259380
 *  Description : BSIMCMG data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiBSIMCMGModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* BSIMCMG model parameters, which need to be updated in omiBSIMCMGTemp.c */
  double u0;
  double dvtshift;

  unsigned u0Given:1;
  unsigned dvtshiftGiven:1;

/* Other Input parameters */
  double omimod;
  double a0;
  double b0;
  double c0;
  double ea0;
  double d0;
  double nox;
  double tsimu;
  double dagetime;

  unsigned omimodGiven:1;
  unsigned a0Given:1;
  unsigned b0Given:1;
  unsigned c0Given:1;
  unsigned ea0Given:1;
  unsigned d0Given:1;
  unsigned noxGiven:1;
  unsigned tsimuGiven:1;
  unsigned dagetimeGiven:1;

} omiBSIMCMGModel;

typedef struct omiBSIMCMGInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* BSIMCMG instance parameters, which need to be used in omiBSIMCMGTemp.c */


/* Other Input parameters */
  double nfin;

  unsigned nfinGiven:1;

} omiBSIMCMGInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define BCMG_INST_SIZE_o  0  /* number of instance parameter (output) */

#define BCMG_INST_nfin          101
/* Model parameter */
#define BCMG_MOD_SIZE_o  2  /* number of model parameter (output) */

#define BCMG_MOD_u0                             0
#define BCMG_MOD_dvtshift                       1

#define BCMG_MOD_omimod                         1001
#define BCMG_MOD_a0                             1002
#define BCMG_MOD_b0                             1003
#define BCMG_MOD_c0                             1004
#define BCMG_MOD_ea0                            1005
#define BCMG_MOD_d0                             1006
#define BCMG_MOD_nox                            1007
#define BCMG_MOD_tsimu                          1008
#define BCMG_MOD_dagetime                       1009

extern String    omi_bcmg_inst_param_o[BCMG_INST_SIZE_o];
extern double  *omi_bcmg_inst_value_o;
extern String    omi_bcmg_mod_param_o[BCMG_MOD_SIZE_o];
extern double  *omi_bcmg_mod_value_o;
extern omiSelectModelBin *omi_bcmg_mod_bin;
extern parNode *omiBSIMCMGInstHeader;
extern parNode *omiBSIMCMGModelHeader;


int    omiBSIMCMGInitModelParam (omiBSIMCMGModel *pBSIMCMGModel);
int    omiBSIMCMGAssignModelParam (omiModel *pModel, omiBSIMCMGModel *pBSIMCMGModel);
ParamId omiBSIMCMGGetModelParamIdByName (String aName);
int    omiBSIMCMGSetModelParam (omiBSIMCMGModel *pBSIMCMGModel, String aName, double aValue);
int    omiBSIMCMGSetModelParamDefault (omiBSIMCMGModel *pBSIMCMGModel);
int    omiBSIMCMGPrintModel (omiModel *pModel, omiBSIMCMGModel *pBSIMCMGModel);
int    omiBSIMCMGInitInstParam (omiBSIMCMGInstance *pBSIMCMGInst);
int    omiBSIMCMGAssignInstParam (omiInstance *pInstance, omiBSIMCMGInstance *pBSIMCMGInst);
ParamId omiBSIMCMGGetInstParamIdByName (String aName);
int    omiBSIMCMGSetInstParam (omiBSIMCMGInstance *pBSIMCMGInst, String aName, double aValue);
int    omiBSIMCMGSetInstParamDefault (omiCKT *pCKT, omiBSIMCMGModel *pBSIMCMGModel, omiBSIMCMGInstance *pBSIMCMGInst);
int    omiBSIMCMGTemp (omiCKT *pCKT, omiBSIMCMGModel *pBSIMCMGModel, omiBSIMCMGInstance *pBSIMCMGInst);
int    omiBSIMCMGCheckModel (omiInstance *pInstance, omiBSIMCMGModel *pBSIMCMGModel, omiBSIMCMGInstance *pBSIMCMGInst);
void     omiBSIMCMGBuildInstParam ();
void     omiBSIMCMGBuildModelParam ();
void    omiBSIMCMGRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiBSIMCMGCoreData
{
  double ids;
  double igidl;
  double igisl;
  double igs;
  double igd;
  double igcs;
  double igcd;
  double igbs;
  double igbd;
  double iii;
  double qg;
  double qd;
  double qs;
  double qb;
  double rsgeo;
  double rdgeo;
  double cfgeo;
  double gm;
  double gds;
} omiBSIMCMGCoreData;

#define BCMG_CORE_DATA_SIZE  19  /* number of core data variables */
extern String  omi_bcmg_core_data_param[BCMG_CORE_DATA_SIZE];

/* end of omiBSIMCMGDef.h */
