/*
 *************************************************
 *  File        : omiBSIMCMGBuildParam.c
 *  Date        : 2024-03-15 17:26:35.259773
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiBSIMCMGDef.h"


/* instance parameter (output) name array */
static char   bcmg_inst_param_o[BCMG_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double bcmg_inst_value_o[BCMG_INST_SIZE_o];

/* model parameter (output) name array */
static char   bcmg_mod_param_o[BCMG_MOD_SIZE_o][PARAM_LEN] =
{
  "u0",
  "dvtshift",
};

/* model parameter (output) value array */
static double bcmg_mod_value_o[BCMG_MOD_SIZE_o];

static omiSelectModelBin bcmg_mod_bin;

String  omi_bcmg_inst_param_o[BCMG_INST_SIZE_o];
double *omi_bcmg_inst_value_o = bcmg_inst_value_o;
String  omi_bcmg_mod_param_o[BCMG_MOD_SIZE_o];
double *omi_bcmg_mod_value_o = bcmg_mod_value_o;
omiSelectModelBin *omi_bcmg_mod_bin = &bcmg_mod_bin;

parNode *omiBSIMCMGInstHeader = NULL;
parNode *omiBSIMCMGModelHeader = NULL;

void omiBSIMCMGBuildInstParam ()
{
  int i = 0;

  if (omiBSIMCMGInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiBSIMCMGInstHeader, "nfin", BCMG_INST_nfin);

  for (i = 0; i < BCMG_INST_SIZE_o; i++)
    omi_bcmg_inst_param_o[i] = bcmg_inst_param_o[i];

  return;
}


void omiBSIMCMGBuildModelParam ()
{
  int i = 0;

  if (omiBSIMCMGModelHeader != NULL)
    return;

  omiInsertNode(&omiBSIMCMGModelHeader, "u0", BCMG_MOD_u0);
  omiInsertNode(&omiBSIMCMGModelHeader, "dvtshift", BCMG_MOD_dvtshift);

  /* Other Input parameters */

  omiInsertNode(&omiBSIMCMGModelHeader, "omimod", BCMG_MOD_omimod);
  omiInsertNode(&omiBSIMCMGModelHeader, "a0", BCMG_MOD_a0);
  omiInsertNode(&omiBSIMCMGModelHeader, "b0", BCMG_MOD_b0);
  omiInsertNode(&omiBSIMCMGModelHeader, "c0", BCMG_MOD_c0);
  omiInsertNode(&omiBSIMCMGModelHeader, "ea0", BCMG_MOD_ea0);
  omiInsertNode(&omiBSIMCMGModelHeader, "d0", BCMG_MOD_d0);
  omiInsertNode(&omiBSIMCMGModelHeader, "nox", BCMG_MOD_nox);
  omiInsertNode(&omiBSIMCMGModelHeader, "tsimu", BCMG_MOD_tsimu);
  omiInsertNode(&omiBSIMCMGModelHeader, "dagetime", BCMG_MOD_dagetime);

  for (i = 0; i < BCMG_MOD_SIZE_o; i++)
    omi_bcmg_mod_param_o[i] = bcmg_mod_param_o[i];

  return;
}

static char bcmg_core_data_param[BCMG_CORE_DATA_SIZE][PARAM_LEN] =
{
  "ids",
  "igidl",
  "igisl",
  "igs",
  "igd",
  "igcs",
  "igcd",
  "igbs",
  "igbd",
  "iii",
  "qg",
  "qd",
  "qs",
  "qb",
  "rsgeo",
  "rdgeo",
  "cfgeo",
  "gm",
  "gds",
};

String omi_bcmg_core_data_param[BCMG_CORE_DATA_SIZE];

void omiBSIMCMGBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < BCMG_CORE_DATA_SIZE; i++)
    omi_bcmg_core_data_param[i] = bcmg_core_data_param[i];

  return;
}

/* end of omiBSIMCMGBuildParam.c */
