#****************************************************************************
#  Copyright (c) 2010 Taiwan Semiconductor Manufacturing Company, Ltd.
#  Copyright (c) 2017-2021 Silicon Integration Initiative, Inc.
#  See the file Si2_OMI_Licensed_Package_Statement_v1.0.txt
#  included with this distribution for usage terms and conditions.
#****************************************************************************
#  File        : gen_param_code.py
#  Date        : 2019_0726
#  Description : Python 2.x script to generate parameter parsing code

import re, datetime, sys

class omimod:
    def __init__(self,MID,MABV,paramfile):
        self.mid=MID.lower()
        self.MID=MID
        self.mabv=MABV.lower()
        self.MABV=MABV
        self.param={}
        self.param['modout']=[]
        self.param['modoth']=[]
        self.param['instout']=[]
        self.param['instoth']=[]        
        self.param['core']=[]        
        section = None
        workinglist = []
        f=open(paramfile)
        for line in f:
            if not line.strip():
                # Empty line
                continue
            m=re.search(r'^\s*#',line)
            if m:
                # Comment
                continue
            m=re.search(r'^\s*MODEL\s+OUTPUT\s*$',line)
            if m:
                section='modout'
                continue
            m=re.search(r'^\s*MODEL\s+OTHER\s*$',line)
            if m:
                section='modoth'
                continue
            m=re.search(r'^\s*INSTANCE\s+OUTPUT\s*$',line)
            if m:
                section='instout'
                continue
            m=re.search(r'^\s*INSTANCE\s+OTHER\s*$',line)
            if m:
                section='instoth'
                continue
            m=re.search(r'^\s*CORE\s+DATA\s*$',line)
            if m:
                section='core'
                continue
            self.param[section].append(line.strip().split())
        f.close()

    def writeDef(self):
        f=open('omi'+self.MID+'Def.h','w')
        f.write('''/*
 *************************************************
 *  File        : omi'''+self.MID+'''Def.h
 *  Date        : '''+str(datetime.datetime.today())+'''
 *  Description : '''+self.MID+''' data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omi'''+self.MID+'''Model
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
''')
        f.write('/* '+self.MID+' model parameters, which need to be updated in omi'+self.MID+'Temp.c */\n')
        for p in self.param['modout']:
            f.write('  double '+p[0].lower()+';\n')
        f.write('\n')
        for p in self.param['modout']:
            f.write('  unsigned '+p[0].lower()+'Given:1;\n')
        f.write('\n')
        f.write('/* Other Input parameters */\n')
        for p in self.param['modoth']:
            f.write('  double '+p[0].lower()+';\n')
        f.write('\n')
        for p in self.param['modoth']:
            f.write('  unsigned '+p[0].lower()+'Given:1;\n')
        f.write('\n')
        f.write('''} omi'''+self.MID+'''Model;

typedef struct omi'''+self.MID+'''Instance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
''')
        
        f.write('/* '+self.MID+' instance parameters, which need to be used in omi'+self.MID+'Temp.c */\n')
        for p in self.param['instout']:
            f.write('  double '+p[0].lower()+';\n')
        f.write('\n')
        for p in self.param['instout']:
            f.write('  unsigned '+p[0].lower()+'Given:1;\n')
        f.write('\n')
        f.write('/* Other Input parameters */\n')
        for p in self.param['instoth']:
            f.write('  double '+p[0].lower()+';\n')
        f.write('\n')
        for p in self.param['instoth']:
            f.write('  unsigned '+p[0].lower()+'Given:1;\n')
        f.write('\n')
        f.write('''} omi'''+self.MID+'''Instance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define '''+self.MABV+'''_INST_SIZE_o  '''+str(len(self.param['instout']))+'''  /* number of instance parameter (output) */
''')
        i=0
        for p in self.param['instout']:
            numstr=' '*(14-len(p[0]))
            f.write('#define '+self.MABV+'_INST_'+p[0].lower()+numstr+str(i)+'\n')
            i=i+1
        f.write('\n')
        i=101
        for p in self.param['instoth']:
            numstr=' '*(14-len(p[0]))
            f.write('#define '+self.MABV+'_INST_'+p[0].lower()+numstr+str(i)+'\n')
            i=i+1
        f.write('/* Model parameter */\n')            
        f.write('#define '+self.MABV+'_MOD_SIZE_o  '+str(len(self.param['modout']))+'  /* number of model parameter (output) */\n')            
        f.write('\n')            
        i=0
        for p in self.param['modout']:
            numstr=' '*(31-len(p[0]))
            f.write('#define '+self.MABV+'_MOD_'+p[0].lower()+numstr+str(i)+'\n')
            i=i+1
        f.write('\n')
        i=1001
        for p in self.param['modoth']:
            numstr=' '*(31-len(p[0]))
            f.write('#define '+self.MABV+'_MOD_'+p[0].lower()+numstr+str(i)+'\n')
            i=i+1
        f.write('\n')            
        f.write('extern String    omi_'+self.mabv+'_inst_param_o['+self.MABV+'_INST_SIZE_o];\n')
        f.write('extern double  *omi_'+self.mabv+'_inst_value_o;\n')
        f.write('extern String    omi_'+self.mabv+'_mod_param_o['+self.MABV+'_MOD_SIZE_o];\n')
        f.write('extern double  *omi_'+self.mabv+'_mod_value_o;\n')
        f.write('extern omiSelectModelBin *omi_'+self.mabv+'_mod_bin;\n')
        f.write('extern parNode *omi'+self.MID+'InstHeader;\n')
        f.write('extern parNode *omi'+self.MID+'ModelHeader;\n')
        f.write('''

int    omi'''+self.MID+'''InitModelParam (omi'''+self.MID+'''Model *p'''+self.MID+'''Model);
int    omi'''+self.MID+'''AssignModelParam (omiModel *pModel, omi'''+self.MID+'''Model *p'''+self.MID+'''Model);
ParamId omi'''+self.MID+'''GetModelParamIdByName (String aName);
int    omi'''+self.MID+'''SetModelParam (omi'''+self.MID+'''Model *p'''+self.MID+'''Model, String aName, double aValue);
int    omi'''+self.MID+'''SetModelParamDefault (omi'''+self.MID+'''Model *p'''+self.MID+'''Model);
int    omi'''+self.MID+'''PrintModel (omiModel *pModel, omi'''+self.MID+'''Model *p'''+self.MID+'''Model);
int    omi'''+self.MID+'''InitInstParam (omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst);
int    omi'''+self.MID+'''AssignInstParam (omiInstance *pInstance, omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst);
ParamId omi'''+self.MID+'''GetInstParamIdByName (String aName);
int    omi'''+self.MID+'''SetInstParam (omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst, String aName, double aValue);
int    omi'''+self.MID+'''SetInstParamDefault (omiCKT *pCKT, omi'''+self.MID+'''Model *p'''+self.MID+'''Model, omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst);
int    omi'''+self.MID+'''Temp (omiCKT *pCKT, omi'''+self.MID+'''Model *p'''+self.MID+'''Model, omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst);
int    omi'''+self.MID+'''CheckModel (omiInstance *pInstance, omi'''+self.MID+'''Model *p'''+self.MID+'''Model, omi'''+self.MID+'''Instance *p'''+self.MID+'''Inst);
void     omi'''+self.MID+'''BuildInstParam ();
void     omi'''+self.MID+'''BuildModelParam ();
void    omi'''+self.MID+'''RegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omi'''+self.MID+'''CoreData
{
''')
        for p in self.param['core']:
            f.write('  double '+p[0].lower()+';\n')
        f.write('} omi'+self.MID+'CoreData;\n\n')
        f.write('#define '+self.MABV+'_CORE_DATA_SIZE  '+str(len(self.param['core']))+'  /* number of core data variables */\n')            
        f.write('extern String  omi_'+self.mabv+'_core_data_param['+self.MABV+'_CORE_DATA_SIZE];\n\n')
        f.write('/* end of omi'+self.MID+'Def.h */\n')
        f.close()

    def writeSet(self):
        f=open('omi'+self.MID+'Set.c','w')
        f.write('''/*
 *************************************************
 *  File        : omi'''+self.MID+'''Set.c
 *  Date        : '''+str(datetime.datetime.today())+'''
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omi'''+self.MID+'''Def.h"

''')
        f.write('int omi'+self.MID+'SetModelParamDefault (omi'+self.MID+'Model *p'+self.MID+'Model)\n')
        f.write('\n')
        f.write('{\n')
        for p in self.param['modout']:
            f.write('  if (!p'+self.MID+'Model->'+p[0].lower()+'Given)\n')
            if len(p)==2:
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
            elif len(p)==4:
                f.write('  {\n')
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    if (p'+self.MID+p[3]+') p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
                try:
                    valstr=str(float(p[2]))
                except ValueError:
                    valstr='p'+self.MID+p[2]
                f.write('    else p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
                f.write('  }\n')
        f.write('\n')
        f.write('  /*  Other Input Parameters */\n')
        f.write('\n')
        for p in self.param['modoth']:
            f.write('  if (!p'+self.MID+'Model->'+p[0].lower()+'Given)\n')
            if len(p)==2:
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
            elif len(p)==4:
                f.write('  {\n')
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    if (p'+self.MID+p[3]+') p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
                try:
                    valstr=str(float(p[2]))
                except ValueError:
                    valstr='p'+self.MID+p[2]
                f.write('    else p'+self.MID+'Model->'+p[0].lower()+' = '+valstr+';\n')
                f.write('  }\n')
        f.write('\n')
        f.write('  return OMI_OK;\n')
        f.write('}\n')
        f.write('\n')
        f.write('\n')
        f.write('int omi'+self.MID+'SetInstParamDefault (omiCKT *pCKT, omi'+self.MID+'Model *p'+self.MID+'Model, omi'+self.MID+'Instance *p'+self.MID+'Inst)\n')
        f.write('{\n')
        f.write('\n')
        for p in self.param['instout']:
            f.write('  if (!p'+self.MID+'Inst->'+p[0].lower()+'Given)\n')
            if len(p)==2:
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
            elif len(p)==4:
                f.write('  {\n')
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    if (p'+self.MID+p[3]+') p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
                try:
                    valstr=str(float(p[2]))
                except ValueError:
                    valstr='p'+self.MID+p[2]
                f.write('    else p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
                f.write('  }\n')
        f.write('\n')
        f.write('  /*  Other Input Parameters */\n')
        f.write('\n')
        for p in self.param['instoth']:
            f.write('  if (!p'+self.MID+'Inst->'+p[0].lower()+'Given)\n')
            if len(p)==2:
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
            elif len(p)==4:
                f.write('  {\n')
                try:
                    valstr=str(float(p[1]))
                except ValueError:
                    valstr='p'+self.MID+p[1]
                f.write('    if (p'+self.MID+p[3]+') p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
                try:
                    valstr=str(float(p[2]))
                except ValueError:
                    valstr='p'+self.MID+p[2]
                f.write('    else p'+self.MID+'Inst->'+p[0].lower()+' = '+valstr+';\n')
                f.write('  }\n')
        f.write('\n')
        f.write('  return OMI_OK;\n')
        f.write('}\n')
        f.write('\n')
        f.write('''
int omi'''+self.MID+'''PrintModel (omiModel *pModel, omi'''+self.MID+'''Model *p'''+self.MID+'''Model)
{
  if (!p'''+self.MID+'''Model->printModel)
    return OMI_OK;


  return OMI_OK;
}
''')
        f.write('/* end of omi'+self.MID+'Set.c */\n')
        f.close()
                


    def writeBuildParam(self):
        f=open('omi'+self.MID+'BuildParam.c','w')
        f.write('''/*
 *************************************************
 *  File        : omi'''+self.MID+'''BuildParam.c
 *  Date        : '''+str(datetime.datetime.today())+'''
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omi'''+self.MID+'''Def.h"


/* instance parameter (output) name array */
''')
        f.write('static char   '+self.mabv+'_inst_param_o['+self.MABV+'_INST_SIZE_o][PARAM_LEN] =\n')
        f.write('{\n')
        for p in self.param['instout']:
            f.write('  "'+p[0].lower()+'",\n')
        f.write('};\n')
        f.write('\n')
        f.write('/* instance parameter (output) value array */\n')
        f.write('static double '+self.mabv+'_inst_value_o['+self.MABV+'_INST_SIZE_o];\n')
        f.write('\n')
        f.write('/* model parameter (output) name array */\n')
        f.write('static char   '+self.mabv+'_mod_param_o['+self.MABV+'_MOD_SIZE_o][PARAM_LEN] =\n')
        f.write('{\n')
        for p in self.param['modout']:
            f.write('  "'+p[0].lower()+'",\n')
        f.write('};\n')
        f.write('\n')

        f.write('/* model parameter (output) value array */\n')
        f.write('static double '+self.mabv+'_mod_value_o['+self.MABV+'_MOD_SIZE_o];\n')
        f.write('\n')
        f.write('static omiSelectModelBin '+self.mabv+'_mod_bin;\n')
        f.write('\n')
        f.write('String  omi_'+self.mabv+'_inst_param_o['+self.MABV+'_INST_SIZE_o];\n')
        f.write('double *omi_'+self.mabv+'_inst_value_o = '+self.mabv+'_inst_value_o;\n')
        f.write('String  omi_'+self.mabv+'_mod_param_o['+self.MABV+'_MOD_SIZE_o];\n')
        f.write('double *omi_'+self.mabv+'_mod_value_o = '+self.mabv+'_mod_value_o;\n')
        f.write('omiSelectModelBin *omi_'+self.mabv+'_mod_bin = &'+self.mabv+'_mod_bin;\n')
        f.write('\n')
        f.write('parNode *omi'+self.MID+'InstHeader = NULL;\n')
        f.write('parNode *omi'+self.MID+'ModelHeader = NULL;\n')
        f.write('\n')
        f.write('void omi'+self.MID+'BuildInstParam ()\n')
        f.write('{\n')
        f.write('  int i = 0;\n')
        f.write('\n')
        f.write('  if (omi'+self.MID+'InstHeader != NULL)\n')
        f.write('    return;\n')
        for p in self.param['instout']:
            f.write('  omiInsertNode(&omi'+self.MID+'InstHeader, "'+p[0].lower()+'", '+self.MABV+'_INST_'+p[0].lower()+');\n')
        f.write('\n')
        f.write('  /* Other Input parameters */\n')
        f.write('\n')
        for p in self.param['instoth']:
            f.write('  omiInsertNode(&omi'+self.MID+'InstHeader, "'+p[0].lower()+'", '+self.MABV+'_INST_'+p[0].lower()+');\n')
        f.write('\n')
        f.write('  for (i = 0; i < '+self.MABV+'_INST_SIZE_o; i++)\n')
        f.write('    omi_'+self.mabv+'_inst_param_o[i] = '+self.mabv+'_inst_param_o[i];\n')
        f.write('\n')
        f.write('  return;\n')
        f.write('}\n')
        f.write('\n')
        f.write('\n')
        f.write('void omi'+self.MID+'BuildModelParam ()\n')
        f.write('{\n')
        f.write('  int i = 0;\n')
        f.write('\n')
        f.write('  if (omi'+self.MID+'ModelHeader != NULL)\n')
        f.write('    return;\n')
        f.write('\n')
        for p in self.param['modout']:
            f.write('  omiInsertNode(&omi'+self.MID+'ModelHeader, "'+p[0].lower()+'", '+self.MABV+'_MOD_'+p[0].lower()+');\n')
        f.write('\n')
        f.write('  /* Other Input parameters */\n')
        f.write('\n')
        for p in self.param['modoth']:
            f.write('  omiInsertNode(&omi'+self.MID+'ModelHeader, "'+p[0].lower()+'", '+self.MABV+'_MOD_'+p[0].lower()+');\n')
        f.write('\n')
        f.write('  for (i = 0; i < '+self.MABV+'_MOD_SIZE_o; i++)\n')
        f.write('    omi_'+self.mabv+'_mod_param_o[i] = '+self.mabv+'_mod_param_o[i];\n')
        f.write('\n')
        f.write('  return;\n')
        f.write('}\n')
        f.write('\n')
        f.write('static char '+self.mabv+'_core_data_param['+self.MABV+'_CORE_DATA_SIZE][PARAM_LEN] =\n')
        f.write('{\n')
        for p in self.param['core']:
            f.write('  "'+p[0].lower()+'",\n')
        f.write('};\n')
        f.write('\n')
        f.write('String omi_'+self.mabv+'_core_data_param['+self.MABV+'_CORE_DATA_SIZE];\n')
        f.write('\n')
        f.write('void omi'+self.MID+'BuildCoreDataParam ()\n')
        f.write('{\n')
        f.write('  int i = 0;\n')
        f.write('\n')
        f.write('  for (i = 0; i < '+self.MABV+'_CORE_DATA_SIZE; i++)\n')
        f.write('    omi_'+self.mabv+'_core_data_param[i] = '+self.mabv+'_core_data_param[i];\n')
        f.write('\n')
        f.write('  return;\n')
        f.write('}\n')
        f.write('\n')
        f.write('/* end of omi'+self.MID+'BuildParam.c */\n')
        f.close()

        
                


    def writeInitParam(self):
        for section in ['Model','Instance']:
            if section=='Model':
                sectprefix='mod'
                sectabv='Model'
            else:
                sectprefix='inst'
                sectabv='Inst'
            f=open('omi'+self.MID+'Init'+sectabv+'Param.c','w')
            f.write('''/*
 *************************************************
 *  File        : omi'''+self.MID+'''Init'''+sectabv+'''Param.c
 *  Date        : '''+str(datetime.datetime.today())+'''
 *  Description : To initialize '''+section.lower()+''' parameters
 *                Generated by gen_param_code.py
 */

#include "omi'''+self.MID+'''Def.h"


''')
            f.write('int omi'+self.MID+'Init'+sectabv+'Param (omi'+self.MID+section+' *p'+self.MID+sectabv+')\n')
            f.write('{\n')
            for p in self.param[sectprefix+'out']:
                f.write('  p'+self.MID+sectabv+'->'+p[0].lower()+'Given=0;\n')
            f.write('\n')
            f.write('  /* Other Input parameters */\n')
            f.write('\n')
            for p in self.param[sectprefix+'oth']:
                f.write('  p'+self.MID+sectabv+'->'+p[0].lower()+'Given=0;\n')
            f.write('\n')
            f.write('  return OMI_OK;\n')
            f.write('}\n')
            f.write('/* end of omi'+self.MID+'Init'+sectabv+'Param.c */\n')
            f.close()
        

    def writeSetParam(self):
        for section in ['Model','Instance']:
            if section=='Model':
                sectprefix='mod'
                sectabv='Model'
            else:
                sectprefix='inst'
                sectabv='Inst'
            f=open('omi'+self.MID+'Set'+sectabv+'Param.c','w')
            f.write('''/*
 *************************************************
 *  File        : omi'''+self.MID+'''Set'''+sectabv+'''Param.c
 *  Date        : '''+str(datetime.datetime.today())+'''
 *  Description : To get '''+section.lower()+''' parameter values
 *                Generated by gen_param_code.py
 */

#include "omi'''+self.MID+'''Def.h"


''')
            f.write('int omi'+self.MID+'Set'+sectabv+'Param (omi'+self.MID+section+' *p'+self.MID+sectabv+', String aName, double aValue)\n')
            f.write('{\n')
            f.write('  switch(omi'+self.MID+'Get'+sectabv+'ParamIdByName(aName))\n')
            f.write('  {\n')

            for p in self.param[sectprefix+'out']:
                f.write('    case '+self.MABV+'_'+sectprefix.upper()+'_'+p[0].lower()+':\n')
                f.write('      p'+self.MID+sectabv+'->'+p[0].lower()+' = aValue;\n')
                f.write('      p'+self.MID+sectabv+'->'+p[0].lower()+'Given = TRUE;\n')
                f.write('      break;\n')
            f.write('\n')
            f.write('  /* Other Input parameters */\n')
            f.write('\n')
            for p in self.param[sectprefix+'oth']:
                f.write('    case '+self.MABV+'_'+sectprefix.upper()+'_'+p[0].lower()+':\n')
                f.write('      p'+self.MID+sectabv+'->'+p[0].lower()+' = aValue;\n')
                f.write('      p'+self.MID+sectabv+'->'+p[0].lower()+'Given = TRUE;\n')
                f.write('      break;\n')
            f.write('    default:\n')
            f.write('      break;\n')
            f.write('  }\n')
            f.write('\n')
            f.write('  return OMI_OK;\n')
            f.write('}\n')
            f.write('/* end of omi'+self.MID+'Set'+sectabv+'Param.c */\n')
            f.close()


    def writeTempInc(self):
        f=open('omi'+self.MID+'Temp.inc','w')
        f.write('''  /*
   *************************************************
   *  File        : omi'''+self.MID+'''Temp.inc
   *  Date        : '''+str(datetime.datetime.today())+'''
   *  Description : Template parameter update code for omi'''+self.MID+'''Temp.c
   *                Generated by gen_param_code.py
   */

  /* set instance parameters */
''')
        for p in self.param['instout']:
            f.write('  omi_'+self.mabv+'_inst_value_o['+self.MABV+'_INST_'+p[0].lower()+'] = p'+self.MID+'Inst->'+p[0].lower()+';\n')
        f.write('\n')
        f.write('  /* update model parameters */\n')
        for p in self.param['modout']:
            f.write('  omi_'+self.mabv+'_mod_value_o['+self.MABV+'_MOD_'+p[0].lower()+'] = p'+self.MID+'Model->'+p[0].lower()+';\n')
        f.close()
        
om=omimod(sys.argv[1],sys.argv[2],'parameters')
om.writeDef()
om.writeSet()
om.writeBuildParam()
om.writeInitParam()
om.writeSetParam()
om.writeTempInc()
