/*
 *************************************************
 *  File        : omiBSIMSOIBuildParam.c
 *  Date        : 2024-03-15 16:24:23.449043
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiBSIMSOIDef.h"


/* instance parameter (output) name array */
static char   bsoi_inst_param_o[BSOI_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double bsoi_inst_value_o[BSOI_INST_SIZE_o];

/* model parameter (output) name array */
static char   bsoi_mod_param_o[BSOI_MOD_SIZE_o][PARAM_LEN] =
{
  "vth0",
};

/* model parameter (output) value array */
static double bsoi_mod_value_o[BSOI_MOD_SIZE_o];

static omiSelectModelBin bsoi_mod_bin;

String  omi_bsoi_inst_param_o[BSOI_INST_SIZE_o];
double *omi_bsoi_inst_value_o = bsoi_inst_value_o;
String  omi_bsoi_mod_param_o[BSOI_MOD_SIZE_o];
double *omi_bsoi_mod_value_o = bsoi_mod_value_o;
omiSelectModelBin *omi_bsoi_mod_bin = &bsoi_mod_bin;

parNode *omiBSIMSOIInstHeader = NULL;
parNode *omiBSIMSOIModelHeader = NULL;

void omiBSIMSOIBuildInstParam ()
{
  int i = 0;

  if (omiBSIMSOIInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiBSIMSOIInstHeader, "w", BSOI_INST_w);

  for (i = 0; i < BSOI_INST_SIZE_o; i++)
    omi_bsoi_inst_param_o[i] = bsoi_inst_param_o[i];

  return;
}


void omiBSIMSOIBuildModelParam ()
{
  int i = 0;

  if (omiBSIMSOIModelHeader != NULL)
    return;

  omiInsertNode(&omiBSIMSOIModelHeader, "vth0", BSOI_MOD_vth0);

  /* Other Input parameters */

  omiInsertNode(&omiBSIMSOIModelHeader, "omimod", BSOI_MOD_omimod);

  for (i = 0; i < BSOI_MOD_SIZE_o; i++)
    omi_bsoi_mod_param_o[i] = bsoi_mod_param_o[i];

  return;
}

static char bsoi_core_data_param[BSOI_CORE_DATA_SIZE][PARAM_LEN] =
{
  "ids",
  "igidl",
  "igisl",
  "igs",
  "igd",
  "igcs",
  "igcd",
  "igb",
  "ibs",
  "ibd",
  "ic",
  "vdsat",
  "vth",
  "gm",
  "gmbs",
  "gds",
};

String omi_bsoi_core_data_param[BSOI_CORE_DATA_SIZE];

void omiBSIMSOIBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < BSOI_CORE_DATA_SIZE; i++)
    omi_bsoi_core_data_param[i] = bsoi_core_data_param[i];

  return;
}

/* end of omiBSIMSOIBuildParam.c */
