/*
 *************************************************
 *  File        : omiBSIMSOISetModelParam.c
 *  Date        : 2024-03-15 16:24:23.449717
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMSOIDef.h"


int omiBSIMSOISetModelParam (omiBSIMSOIModel *pBSIMSOIModel, String aName, double aValue)
{
  switch(omiBSIMSOIGetModelParamIdByName(aName))
  {
    case BSOI_MOD_vth0:
      pBSIMSOIModel->vth0 = aValue;
      pBSIMSOIModel->vth0Given = TRUE;
      break;

  /* Other Input parameters */

    case BSOI_MOD_omimod:
      pBSIMSOIModel->omimod = aValue;
      pBSIMSOIModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMSOISetModelParam.c */
