/*
 *************************************************
 *  File        : omiBSIMSOISet.c
 *  Date        : 2024-03-15 16:24:23.448758
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiBSIMSOIDef.h"

int omiBSIMSOISetModelParamDefault (omiBSIMSOIModel *pBSIMSOIModel)

{
  if (!pBSIMSOIModel->vth0Given)
  {
    if (pBSIMSOIModel->modelType==NMOS) pBSIMSOIModel->vth0 = 0.7;
    else pBSIMSOIModel->vth0 = -0.7;
  }

  /*  Other Input Parameters */

  if (!pBSIMSOIModel->omimodGiven)
    pBSIMSOIModel->omimod = 0.0;

  return OMI_OK;
}


int omiBSIMSOISetInstParamDefault (omiCKT *pCKT, omiBSIMSOIModel *pBSIMSOIModel, omiBSIMSOIInstance *pBSIMSOIInst)
{


  /*  Other Input Parameters */

  if (!pBSIMSOIInst->wGiven)
    pBSIMSOIInst->w = 5e-06;

  return OMI_OK;
}


int omiBSIMSOIPrintModel (omiModel *pModel, omiBSIMSOIModel *pBSIMSOIModel)
{
  if (!pBSIMSOIModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiBSIMSOISet.c */
