/*
 *************************************************
 *  File        : omiBSIMSOIDef.h
 *  Date        : 2024-03-15 16:24:23.448485
 *  Description : BSIMSOI data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiBSIMSOIModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* BSIMSOI model parameters, which need to be updated in omiBSIMSOITemp.c */
  double vth0;

  unsigned vth0Given:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiBSIMSOIModel;

typedef struct omiBSIMSOIInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* BSIMSOI instance parameters, which need to be used in omiBSIMSOITemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiBSIMSOIInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define BSOI_INST_SIZE_o  0  /* number of instance parameter (output) */

#define BSOI_INST_w             101
/* Model parameter */
#define BSOI_MOD_SIZE_o  1  /* number of model parameter (output) */

#define BSOI_MOD_vth0                           0

#define BSOI_MOD_omimod                         1001

extern String    omi_bsoi_inst_param_o[BSOI_INST_SIZE_o];
extern double  *omi_bsoi_inst_value_o;
extern String    omi_bsoi_mod_param_o[BSOI_MOD_SIZE_o];
extern double  *omi_bsoi_mod_value_o;
extern omiSelectModelBin *omi_bsoi_mod_bin;
extern parNode *omiBSIMSOIInstHeader;
extern parNode *omiBSIMSOIModelHeader;


int    omiBSIMSOIInitModelParam (omiBSIMSOIModel *pBSIMSOIModel);
int    omiBSIMSOIAssignModelParam (omiModel *pModel, omiBSIMSOIModel *pBSIMSOIModel);
ParamId omiBSIMSOIGetModelParamIdByName (String aName);
int    omiBSIMSOISetModelParam (omiBSIMSOIModel *pBSIMSOIModel, String aName, double aValue);
int    omiBSIMSOISetModelParamDefault (omiBSIMSOIModel *pBSIMSOIModel);
int    omiBSIMSOIPrintModel (omiModel *pModel, omiBSIMSOIModel *pBSIMSOIModel);
int    omiBSIMSOIInitInstParam (omiBSIMSOIInstance *pBSIMSOIInst);
int    omiBSIMSOIAssignInstParam (omiInstance *pInstance, omiBSIMSOIInstance *pBSIMSOIInst);
ParamId omiBSIMSOIGetInstParamIdByName (String aName);
int    omiBSIMSOISetInstParam (omiBSIMSOIInstance *pBSIMSOIInst, String aName, double aValue);
int    omiBSIMSOISetInstParamDefault (omiCKT *pCKT, omiBSIMSOIModel *pBSIMSOIModel, omiBSIMSOIInstance *pBSIMSOIInst);
int    omiBSIMSOITemp (omiCKT *pCKT, omiBSIMSOIModel *pBSIMSOIModel, omiBSIMSOIInstance *pBSIMSOIInst);
int    omiBSIMSOICheckModel (omiInstance *pInstance, omiBSIMSOIModel *pBSIMSOIModel, omiBSIMSOIInstance *pBSIMSOIInst);
void     omiBSIMSOIBuildInstParam ();
void     omiBSIMSOIBuildModelParam ();
void    omiBSIMSOIRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiBSIMSOICoreData
{
  double ids;
  double igidl;
  double igisl;
  double igs;
  double igd;
  double igcs;
  double igcd;
  double igb;
  double ibs;
  double ibd;
  double ic;
  double vdsat;
  double vth;
  double gm;
  double gmbs;
  double gds;
} omiBSIMSOICoreData;

#define BSOI_CORE_DATA_SIZE  16  /* number of core data variables */
extern String  omi_bsoi_core_data_param[BSOI_CORE_DATA_SIZE];

/* end of omiBSIMSOIDef.h */
