/*
 *************************************************
 *  File        : omiBSIMSOIInitModelParam.c
 *  Date        : 2024-03-15 16:24:23.449303
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMSOIDef.h"


int omiBSIMSOIInitModelParam (omiBSIMSOIModel *pBSIMSOIModel)
{
  pBSIMSOIModel->vth0Given=0;

  /* Other Input parameters */

  pBSIMSOIModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiBSIMSOIInitModelParam.c */
