/*
 *************************************************
 *  File        : omiBSIMSOIInitInstParam.c
 *  Date        : 2024-03-15 16:24:23.449510
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMSOIDef.h"


int omiBSIMSOIInitInstParam (omiBSIMSOIInstance *pBSIMSOIInst)
{

  /* Other Input parameters */

  pBSIMSOIInst->wGiven=0;

  return OMI_OK;
}
/* end of omiBSIMSOIInitInstParam.c */
