/*
 *************************************************
 *  File        : omiBSIMSOISetInstParam.c
 *  Date        : 2024-03-15 16:24:23.449942
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMSOIDef.h"


int omiBSIMSOISetInstParam (omiBSIMSOIInstance *pBSIMSOIInst, String aName, double aValue)
{
  switch(omiBSIMSOIGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case BSOI_INST_w:
      pBSIMSOIInst->w = aValue;
      pBSIMSOIInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMSOISetInstParam.c */
