/*
 *************************************************
 *  File        : omiBSIMIMGSet.c
 *  Date        : 2024-03-15 16:24:24.047173
 *  Description : To set default values
 *                Generated by gen_param_code.py
 */

#include <math.h>
#include "omiBSIMIMGDef.h"

int omiBSIMIMGSetModelParamDefault (omiBSIMIMGModel *pBSIMIMGModel)

{
  if (!pBSIMIMGModel->u0Given)
    pBSIMIMGModel->u0 = 0.03;

  /*  Other Input Parameters */

  if (!pBSIMIMGModel->omimodGiven)
    pBSIMIMGModel->omimod = 0.0;

  return OMI_OK;
}


int omiBSIMIMGSetInstParamDefault (omiCKT *pCKT, omiBSIMIMGModel *pBSIMIMGModel, omiBSIMIMGInstance *pBSIMIMGInst)
{


  /*  Other Input Parameters */

  if (!pBSIMIMGInst->wGiven)
    pBSIMIMGInst->w = 1e-06;

  return OMI_OK;
}


int omiBSIMIMGPrintModel (omiModel *pModel, omiBSIMIMGModel *pBSIMIMGModel)
{
  if (!pBSIMIMGModel->printModel)
    return OMI_OK;


  return OMI_OK;
}
/* end of omiBSIMIMGSet.c */
