/*
 *************************************************
 *  File        : omiBSIMIMGInitInstParam.c
 *  Date        : 2024-03-15 16:24:24.047615
 *  Description : To initialize instance parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMIMGDef.h"


int omiBSIMIMGInitInstParam (omiBSIMIMGInstance *pBSIMIMGInst)
{

  /* Other Input parameters */

  pBSIMIMGInst->wGiven=0;

  return OMI_OK;
}
/* end of omiBSIMIMGInitInstParam.c */
