/*
 *************************************************
 *  File        : omiBSIMIMGDef.h
 *  Date        : 2024-03-15 16:24:24.046986
 *  Description : BSIMIMG data structures
 *                Generated by gen_param_code.py
 */


#include "omiDef.h"
#include "omiBinTree.h"
#include "omiHash.h"
#include "omiAge.h"


#define pwr(A, B) ((A) >= 0 ? pow(fabs(A), B) : (-1 * pow(fabs(A),B)))
#define min(A, B) ((A) > (B) ? (B) : (A))
#define max(A, B) ((A) > (B) ? (A) : (B))
#define abs(A)     ((A) >= 0 ? (A) : -(A))

#define TRUE 1
#define PARAM_LEN 16


typedef struct omiBSIMIMGModel
{
  /* OMI model parameters and paramGiven flags */
  int     modelType;
  int     printModel;
/* BSIMIMG model parameters, which need to be updated in omiBSIMIMGTemp.c */
  double u0;

  unsigned u0Given:1;

/* Other Input parameters */
  double omimod;

  unsigned omimodGiven:1;

} omiBSIMIMGModel;

typedef struct omiBSIMIMGInstance
{
  /* OMI instance parameters and paramGiven flags */
  /* aging instance information */
  char *instName;
  omiSimpleAge *pSimpleAge;

  int printWarn;
/* BSIMIMG instance parameters, which need to be used in omiBSIMIMGTemp.c */


/* Other Input parameters */
  double w;

  unsigned wGiven:1;

} omiBSIMIMGInstance;


/* User can't use -1 (OMI_BADPARAM) for parameter ID */

/* Instance parameter */
#define BIMG_INST_SIZE_o  0  /* number of instance parameter (output) */

#define BIMG_INST_w             101
/* Model parameter */
#define BIMG_MOD_SIZE_o  1  /* number of model parameter (output) */

#define BIMG_MOD_u0                             0

#define BIMG_MOD_omimod                         1001

extern String    omi_bimg_inst_param_o[BIMG_INST_SIZE_o];
extern double  *omi_bimg_inst_value_o;
extern String    omi_bimg_mod_param_o[BIMG_MOD_SIZE_o];
extern double  *omi_bimg_mod_value_o;
extern omiSelectModelBin *omi_bimg_mod_bin;
extern parNode *omiBSIMIMGInstHeader;
extern parNode *omiBSIMIMGModelHeader;


int    omiBSIMIMGInitModelParam (omiBSIMIMGModel *pBSIMIMGModel);
int    omiBSIMIMGAssignModelParam (omiModel *pModel, omiBSIMIMGModel *pBSIMIMGModel);
ParamId omiBSIMIMGGetModelParamIdByName (String aName);
int    omiBSIMIMGSetModelParam (omiBSIMIMGModel *pBSIMIMGModel, String aName, double aValue);
int    omiBSIMIMGSetModelParamDefault (omiBSIMIMGModel *pBSIMIMGModel);
int    omiBSIMIMGPrintModel (omiModel *pModel, omiBSIMIMGModel *pBSIMIMGModel);
int    omiBSIMIMGInitInstParam (omiBSIMIMGInstance *pBSIMIMGInst);
int    omiBSIMIMGAssignInstParam (omiInstance *pInstance, omiBSIMIMGInstance *pBSIMIMGInst);
ParamId omiBSIMIMGGetInstParamIdByName (String aName);
int    omiBSIMIMGSetInstParam (omiBSIMIMGInstance *pBSIMIMGInst, String aName, double aValue);
int    omiBSIMIMGSetInstParamDefault (omiCKT *pCKT, omiBSIMIMGModel *pBSIMIMGModel, omiBSIMIMGInstance *pBSIMIMGInst);
int    omiBSIMIMGTemp (omiCKT *pCKT, omiBSIMIMGModel *pBSIMIMGModel, omiBSIMIMGInstance *pBSIMIMGInst);
int    omiBSIMIMGCheckModel (omiInstance *pInstance, omiBSIMIMGModel *pBSIMIMGModel, omiBSIMIMGInstance *pBSIMIMGInst);
void     omiBSIMIMGBuildInstParam ();
void     omiBSIMIMGBuildModelParam ();
void    omiBSIMIMGRegroupInstParam (omiInstance *pInstance);

/* OMI register function */
void omiRegroupParamReg (omiInstance *pInstance);
 
/* This structure provides convenient access to the Core Data
   operating point variables/parameters used by OMI.
   Prior to OMI 1.1.0, it was defined in omiIft.h  */
typedef struct omiBSIMIMGCoreData
{
  double gds;
} omiBSIMIMGCoreData;

#define BIMG_CORE_DATA_SIZE  1  /* number of core data variables */
extern String  omi_bimg_core_data_param[BIMG_CORE_DATA_SIZE];

/* end of omiBSIMIMGDef.h */
