/*
 *************************************************
 *  File        : omiBSIMIMGSetModelParam.c
 *  Date        : 2024-03-15 16:24:24.047736
 *  Description : To get model parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMIMGDef.h"


int omiBSIMIMGSetModelParam (omiBSIMIMGModel *pBSIMIMGModel, String aName, double aValue)
{
  switch(omiBSIMIMGGetModelParamIdByName(aName))
  {
    case BIMG_MOD_u0:
      pBSIMIMGModel->u0 = aValue;
      pBSIMIMGModel->u0Given = TRUE;
      break;

  /* Other Input parameters */

    case BIMG_MOD_omimod:
      pBSIMIMGModel->omimod = aValue;
      pBSIMIMGModel->omimodGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMIMGSetModelParam.c */
