/*
 *************************************************
 *  File        : omiBSIMIMGInitModelParam.c
 *  Date        : 2024-03-15 16:24:24.047509
 *  Description : To initialize model parameters
 *                Generated by gen_param_code.py
 */

#include "omiBSIMIMGDef.h"


int omiBSIMIMGInitModelParam (omiBSIMIMGModel *pBSIMIMGModel)
{
  pBSIMIMGModel->u0Given=0;

  /* Other Input parameters */

  pBSIMIMGModel->omimodGiven=0;

  return OMI_OK;
}
/* end of omiBSIMIMGInitModelParam.c */
