/*
 *************************************************
 *  File        : omiBSIMIMGBuildParam.c
 *  Date        : 2024-03-15 16:24:24.047376
 *  Description : To build instance/model parameter
 *                Generated by gen_param_code.py
 */

#include "omiBSIMIMGDef.h"


/* instance parameter (output) name array */
static char   bimg_inst_param_o[BIMG_INST_SIZE_o][PARAM_LEN] =
{
};

/* instance parameter (output) value array */
static double bimg_inst_value_o[BIMG_INST_SIZE_o];

/* model parameter (output) name array */
static char   bimg_mod_param_o[BIMG_MOD_SIZE_o][PARAM_LEN] =
{
  "u0",
};

/* model parameter (output) value array */
static double bimg_mod_value_o[BIMG_MOD_SIZE_o];

static omiSelectModelBin bimg_mod_bin;

String  omi_bimg_inst_param_o[BIMG_INST_SIZE_o];
double *omi_bimg_inst_value_o = bimg_inst_value_o;
String  omi_bimg_mod_param_o[BIMG_MOD_SIZE_o];
double *omi_bimg_mod_value_o = bimg_mod_value_o;
omiSelectModelBin *omi_bimg_mod_bin = &bimg_mod_bin;

parNode *omiBSIMIMGInstHeader = NULL;
parNode *omiBSIMIMGModelHeader = NULL;

void omiBSIMIMGBuildInstParam ()
{
  int i = 0;

  if (omiBSIMIMGInstHeader != NULL)
    return;

  /* Other Input parameters */

  omiInsertNode(&omiBSIMIMGInstHeader, "w", BIMG_INST_w);

  for (i = 0; i < BIMG_INST_SIZE_o; i++)
    omi_bimg_inst_param_o[i] = bimg_inst_param_o[i];

  return;
}


void omiBSIMIMGBuildModelParam ()
{
  int i = 0;

  if (omiBSIMIMGModelHeader != NULL)
    return;

  omiInsertNode(&omiBSIMIMGModelHeader, "u0", BIMG_MOD_u0);

  /* Other Input parameters */

  omiInsertNode(&omiBSIMIMGModelHeader, "omimod", BIMG_MOD_omimod);

  for (i = 0; i < BIMG_MOD_SIZE_o; i++)
    omi_bimg_mod_param_o[i] = bimg_mod_param_o[i];

  return;
}

static char bimg_core_data_param[BIMG_CORE_DATA_SIZE][PARAM_LEN] =
{
  "gds",
};

String omi_bimg_core_data_param[BIMG_CORE_DATA_SIZE];

void omiBSIMIMGBuildCoreDataParam ()
{
  int i = 0;

  for (i = 0; i < BIMG_CORE_DATA_SIZE; i++)
    omi_bimg_core_data_param[i] = bimg_core_data_param[i];

  return;
}

/* end of omiBSIMIMGBuildParam.c */
