/*
 *************************************************
 *  File        : omiBSIMIMGSetInstParam.c
 *  Date        : 2024-03-15 16:24:24.047859
 *  Description : To get instance parameter values
 *                Generated by gen_param_code.py
 */

#include "omiBSIMIMGDef.h"


int omiBSIMIMGSetInstParam (omiBSIMIMGInstance *pBSIMIMGInst, String aName, double aValue)
{
  switch(omiBSIMIMGGetInstParamIdByName(aName))
  {

  /* Other Input parameters */

    case BIMG_INST_w:
      pBSIMIMGInst->w = aValue;
      pBSIMIMGInst->wGiven = TRUE;
      break;
    default:
      break;
  }

  return OMI_OK;
}
/* end of omiBSIMIMGSetInstParam.c */
